datreeio/CRDs-catalog

argo/applicationset_v1alpha1.json

feat: add applicationset_v1alpha1 CR

---

Utilities/crd-extractor.sh

https://github.com/datreeio/CRDs-catalog/issues/42

ensure unique filename for each crd

---

helm.toolkit.fluxcd.io/helmrelease_v2beta1.json

Adding HelmRelease_v2beta1 (for flux2).

add helmrelease_v2beta1

---

index.yaml

This change fixes an indentation error on line 359

fix indentation error introduced in #50

---

cert-manager.io/certificate_v1.json
cert-manager.io/certificaterequest_v1.json
cert-manager.io/challenge_v1.json
cert-manager.io/clusterissuer_v1.json
cert-manager.io/issuer_v1.json
cert-manager.io/order_v1.json

Add cert-manager.io

---

projectcontour.io/contourconfiguration_v1alpha1.json
projectcontour.io/contourdeployment_v1alpha1.json
projectcontour.io/extensionservice_v1alpha1.json
projectcontour.io/httpproxy_v1.json
projectcontour.io/tlscertificatedelegation_v1.json

Added [project contour](https://projectcontour.io/docs/main/config/api/) crd schemas

add contour

---

keda.sh/clustertriggerauthentication_v1alpha1.json
keda.sh/scaledjob_v1alpha1.json
keda.sh/scaledobject_v1alpha1.json
keda.sh/triggerauthentication_v1alpha1.json

update KEDA CRDs

---

apiextensions.crossplane.io/compositeresourcedefinition_v1.json
apiextensions.crossplane.io/composition_v1.json
apiextensions.crossplane.io/compositionrevision_v1alpha1.json
pkg.crossplane.io/configuration_v1.json
pkg.crossplane.io/configurationrevision_v1.json
pkg.crossplane.io/controllerconfig_v1alpha1.json
pkg.crossplane.io/lock_v1alpha1.json
pkg.crossplane.io/lock_v1beta1.json
pkg.crossplane.io/provider_v1.json
pkg.crossplane.io/providerrevision_v1.json
secrets.crossplane.io/storeconfig_v1alpha1.json

Hello, thanks for your ready to use catalog which speed up CI checks setup!
I bring https://github.com/crossplane/crossplane public project CRDs
CRDs source: https://github.com/crossplane/crossplane/tree/master/cluster/crds
I have extracted specs using next script:
```
$ kind create cluster
$ helm repo add crossplane-stable https://charts.crossplane.io/stable
$ helm repo update
$ helm upgrade --install crossplane crossplane-stable/crossplane
$ ./crd-extractor.sh
```
Signed-off-by: chobostar <chobostar85@gmail.com>

add crossplane

---

traefik.containo.us/tlsstore_v1alpha1.json

Some new properties were added, see:
https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-tlsstore

Update Traefik `TLSStore` CRD.

---

velero.io/schedule_v1.json

See https://velero.io/docs/v1.9/api-types/schedule/#use.

Add Velero `Schedule` CRD.

---

notification.toolkit.fluxcd.io/alert_v1beta2.json
notification.toolkit.fluxcd.io/provider_v1beta2.json
notification.toolkit.fluxcd.io/receiver_v1beta2.json
source.toolkit.fluxcd.io/ocirepository_v1beta2.json

I added CRDs from https://github.com/fluxcd/flux2/releases/latest/download/crd-schemas.tar.gz that appeared to be missing in this repo.

Add flux v1beta2 CRDs

---

snapshot.storage.k8s.io/volumesnapshot_v1.json
snapshot.storage.k8s.io/volumesnapshot_v1beta1.json
snapshot.storage.k8s.io/volumesnapshotclass_v1.json
snapshot.storage.k8s.io/volumesnapshotclass_v1beta1.json
snapshot.storage.k8s.io/volumesnapshotcontent_v1.json
snapshot.storage.k8s.io/volumesnapshotcontent_v1beta1.json

Adding CRDs originating from
https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
and extracted with `./Utilities/crd-extractor.sh`

Add snapshot.storage.k8s.io CRDs

---

volsync.backube/replicationdestination_v1alpha1.json
volsync.backube/replicationsource_v1alpha1.json

CRDs from https://github.com/backube/volsync

feat: Add volsync CRDs

---

kyverno.io/admissionreport_v1alpha2.json
kyverno.io/backgroundscanreport_v1alpha2.json
kyverno.io/clusteradmissionreport_v1alpha2.json
kyverno.io/clusterbackgroundscanreport_v1alpha2.json
kyverno.io/clusterpolicy_v1.json
kyverno.io/clusterpolicy_v2beta1.json
kyverno.io/clusterreportchangerequest_v1alpha2.json
kyverno.io/generaterequest_v1.json
kyverno.io/policy_v1.json
kyverno.io/policy_v2beta1.json
kyverno.io/reportchangerequest_v1alpha2.json
kyverno.io/updaterequest_v1beta1.json

Add kyverno CRDs from https://github.com/kyverno/kyverno

feat: Add kyverno CRDs

---

cilium.io/ciliumclusterwideenvoyconfig_v2.json
cilium.io/ciliumclusterwidenetworkpolicy_v2.json
cilium.io/ciliumegressgatewaypolicy_v2.json
cilium.io/ciliumendpoint_v2.json
cilium.io/ciliumenvoyconfig_v2.json
cilium.io/ciliumexternalworkload_v2.json
cilium.io/ciliumidentity_v2.json
cilium.io/ciliumlocalredirectpolicy_v2.json
cilium.io/ciliumnetworkpolicy_v2.json
cilium.io/ciliumnode_v2.json

Add cilium CRDs from https://github.com/cilium/cilium
CRDs Source: https://github.com/cilium/cilium/tree/v1.12.6/pkg/k8s/apis/cilium.io/client/crds/v2
I installed them onto a local docker desktop Kubernetes instance and extracted it from there (didn't use helm chart as the CRDs are conditionally installed)

feat: Add cilium CRDs

---

opentelemetry.io/instrumentation_v1alpha1.json
opentelemetry.io/opentelemetrycollector_v1alpha1.json

Add OpenTelemetry Operator CRDs https://github.com/open-telemetry/opentelemetry-operator
CRDs Source: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator/crds
I installed them onto a local docker desktop Kubernetes instance and extracted it from there

feat: Add OpenTelemetry Operator CRDs

---

image.toolkit.fluxcd.io/imagepolicy_v1beta2.json

Missed the update imagepolicy crd. See again [upstream](https://fluxcd.io/flux/components/image/imagepolicies/)

Add image.toolkit.fluxcd.io/imagepolicy_v1beta2

---

apisix.apache.org/apisixclusterconfig_v2.json
apisix.apache.org/apisixclusterconfig_v2beta3.json
apisix.apache.org/apisixconsumer_v2.json
apisix.apache.org/apisixconsumer_v2beta3.json
apisix.apache.org/apisixpluginconfig_v2.json
apisix.apache.org/apisixpluginconfig_v2beta3.json
apisix.apache.org/apisixroute_v2.json
apisix.apache.org/apisixroute_v2beta3.json
apisix.apache.org/apisixtls_v2.json
apisix.apache.org/apisixtls_v2beta3.json
apisix.apache.org/apisixupstream_v2.json
apisix.apache.org/apisixupstream_v2beta3.json

CRDs Source: https://github.com/apache/apisix-ingress-controller/tree/1.6.0/samples/deploy/crd/v1

Add apisix CRDs

---

bitnami.com/sealedsecret_v1alpha1.json

Updated with [crd2jsonschema](https://github.com/tricktron/crd2jsonschema):
`crd2jsonschema -o . https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/master/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml`.

Update Sealed Secrets CRD

---

rabbitmq.com/binding_v1beta1.json
rabbitmq.com/federation_v1beta1.json
rabbitmq.com/permission_v1beta1.json
rabbitmq.com/policy_v1beta1.json
rabbitmq.com/queue_v1beta1.json
rabbitmq.com/rabbitmqcluster_v1beta1.json
rabbitmq.com/schemareplication_v1beta1.json
rabbitmq.com/shovel_v1beta1.json
rabbitmq.com/superstream_v1alpha1.json
rabbitmq.com/topicpermission_v1beta1.json
rabbitmq.com/user_v1beta1.json
rabbitmq.com/vhost_v1beta1.json

Updating rabbit topology and cluster operator schemas with latest.

Update rabbitmq topology and cluster schemas

---

apisix.apache.org/apisixglobalrule_v2.json

CRD Source: https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix-ingress-controller/crds/ApisixGlobalRule.yaml

Add apisix global rule CRD

---

external-secrets.io/clusterexternalsecret_v1beta1.json
external-secrets.io/clustersecretstore_v1alpha1.json
external-secrets.io/clustersecretstore_v1beta1.json
external-secrets.io/externalsecret_v1alpha1.json
external-secrets.io/externalsecret_v1beta1.json
external-secrets.io/pushsecret_v1alpha1.json
external-secrets.io/secretstore_v1alpha1.json
external-secrets.io/secretstore_v1beta1.json
generators.external-secrets.io/fake_v1alpha1.json
generators.external-secrets.io/vaultdynamicsecret_v1alpha1.json

Source: https://github.com/external-secrets/external-secrets/tree/v0.8.3/config/crds/bases

[external-secrets.io] Update CRDs

---

cert-manager.io/certificate_v1.json
cert-manager.io/certificaterequest_v1.json
cert-manager.io/clusterissuer_v1.json
cert-manager.io/issuer_v1.json

Source: https://github.com/cert-manager/cert-manager/tree/v1.12.1/deploy/crds

[cert-manager.io] Update CRDs

---

operator.victoriametrics.com/vmagent_v1beta1.json
operator.victoriametrics.com/vmalert_v1beta1.json
operator.victoriametrics.com/vmalertmanager_v1beta1.json
operator.victoriametrics.com/vmalertmanagerconfig_v1beta1.json
operator.victoriametrics.com/vmauth_v1beta1.json
operator.victoriametrics.com/vmcluster_v1beta1.json
operator.victoriametrics.com/vmnodescrape_v1beta1.json
operator.victoriametrics.com/vmpodscrape_v1beta1.json
operator.victoriametrics.com/vmprobe_v1beta1.json
operator.victoriametrics.com/vmrule_v1beta1.json
operator.victoriametrics.com/vmservicescrape_v1beta1.json
operator.victoriametrics.com/vmsingle_v1beta1.json
operator.victoriametrics.com/vmstaticscrape_v1beta1.json
operator.victoriametrics.com/vmuser_v1beta1.json

Hi, here are the crds obtained with the crd-extractor script for the victoria metrics operator [repo](https://github.com/VictoriaMetrics/helm-charts)
Thanks in advance :)

feat: add victoriametrics crds

---

Utilities/crd-extractor.sh

Refactored to handle cases where a crd `kind` did not match the `singular`
[example](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/crds/gateway.solo.io_v1_MatchableHttpGateway.yaml#L11-L17). And using pre-increment (++NUM_OF_CRDS) to not exit in non-zero.

Refactor to handle `kind` `singular` mismatch

---

secrets.hashicorp.com/vaultauth_v1beta1.json
secrets.hashicorp.com/vaultconnection_v1beta1.json
secrets.hashicorp.com/vaultdynamicsecret_v1beta1.json
secrets.hashicorp.com/vaultpkisecret_v1beta1.json
secrets.hashicorp.com/vaultstaticsecret_v1beta1.json

Add the crds from the new Hashicorp secret Operator

feat(CRD): Add Hashicorp secret operator crds

---

k6.io/k6_v1alpha1.json

Current schema missing newer schema changes, such as seccompProfile property

update k6 operator schema to v0.0.9

---

apps.emqx.io/emqx_v2beta1.json
apps.emqx.io/emqxbroker_v1beta4.json
apps.emqx.io/emqxenterprise_v1beta4.json

upgrade apps.emqx.io to latest version

chore: upgrade apps.emqx.io to latest version

---

operator.victoriametrics.com/vmalert_v1beta1.json
operator.victoriametrics.com/vmnodescrape_v1beta1.json
operator.victoriametrics.com/vmpodscrape_v1beta1.json
operator.victoriametrics.com/vmprobe_v1beta1.json
operator.victoriametrics.com/vmservicescrape_v1beta1.json
operator.victoriametrics.com/vmsingle_v1beta1.json
operator.victoriametrics.com/vmstaticscrape_v1beta1.json

Update to victoriametrics schemas.

Update victoriametrics operator schemas

---

argoproj.io/rollout_v1alpha1.json

Fix https://github.com/datreeio/CRDs-catalog/issues/198

update schema of rollout.argoproj.io/v1alpha1

---

vault.banzaicloud.com/vault_v1alpha1.json

From https://github.com/bank-vaults/vault-operator/

Add banzai Cloud CRD

---

vpcresources.k8s.aws/cninode_v1alpha1.json
vpcresources.k8s.aws/securitygrouppolicy_v1beta1.json

Add CRD definitions from AWS [amazon-vpc-resource-controller-k8s](https://github.com/aws/amazon-vpc-resource-controller-k8s/tree/master/config/crd/bases) controller

Add AWS VPC CNINode, SecurityGroupPolicy CRDs

---

sparkoperator.k8s.io/scheduledsparkapplication_v1beta2.json
sparkoperator.k8s.io/sparkapplication_v1beta2.json

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

Add spark operator CRDs

---

appprotect.f5.com/aplogconf_v1beta1.json
appprotect.f5.com/appolicy_v1beta1.json
appprotect.f5.com/apusersig_v1beta1.json
appprotectdos.f5.com/apdoslogconf_v1beta1.json
appprotectdos.f5.com/apdospolicy_v1beta1.json
appprotectdos.f5.com/dosprotectedresource_v1beta1.json
externaldns.nginx.org/dnsendpoint_v1.json
k8s.nginx.org/globalconfiguration_v1alpha1.json
k8s.nginx.org/policy_v1.json
k8s.nginx.org/policy_v1alpha1.json
k8s.nginx.org/transportserver_v1alpha1.json
k8s.nginx.org/virtualserver_v1.json
k8s.nginx.org/virtualserverroute_v1.json

This PR adds CRDs used in NGINX Ingress Controller
Repo: https://github.com/nginxinc/kubernetes-ingress
CRDs source: https://github.com/nginxinc/kubernetes-ingress/tree/v3.3.0/deployments/common/crds 
```
python ../../../yannh/kubeconform/scripts/openapi2jsonschema.py https://github.com/nginxinc/kubernetes-ingress/raw/v3.3.0/deployments/common/crds/k8s.nginx.org_globalconfigurations.yaml https://github.com/nginxinc/kubernetes-ingress/raw/v3.3.0/deployments/common/crds/k8s.nginx.org_policies.yaml https://github.com/nginxinc/kubernetes-ingress/raw/v3.3.0/deployments/common/crds/k8s.nginx.org_transportservers.yaml https://github.com/nginxinc/kubernetes-ingress/raw/v3.3.0/deployments/common/crds/k8s.nginx.org_virtualserverroutes.yaml …
```

Add nginx CRDs

---

rbacmanager.reactiveops.io/rbacdefinition_v1beta1.json

https://github.com/FairwindsOps/rbac-manager/blob/master/deploy/2_crd.yaml

add rbacmanager CRDs

---

onepassword.com/onepassworditem_v1.json

Fetched from https://github.com/1Password/onepassword-operator/tree/main/config/crd

feat: add onepassword.com CRDs

---

apiextensions.crossplane.io/compositeresourcedefinition_v1.json
apiextensions.crossplane.io/compositionrevision_v1.json
apiextensions.crossplane.io/environmentconfig_v1alpha1.json
apiextensions.crossplane.io/usage_v1alpha1.json
pkg.crossplane.io/controllerconfig_v1alpha1.json
pkg.crossplane.io/deploymentruntimeconfig_v1beta1.json
pkg.crossplane.io/function_v1beta1.json
pkg.crossplane.io/functionrevision_v1beta1.json
pkg.crossplane.io/provider_v1.json
pkg.crossplane.io/providerrevision_v1.json
secrets.crossplane.io/storeconfig_v1alpha1.json

Update Crssplane CRDs to newest version 1.14
Like PR #78 
Same procedure to generate CRD jsons:
```
$ kind create cluster
$ helm repo add crossplane-stable https://charts.crossplane.io/stable
$ helm repo update
$ helm upgrade --install crossplane crossplane-stable/crossplane
$ ./crd-extractor.sh
```

update crossplane CRDs to 1.14

---

resources.teleport.dev/teleportgithubconnector_v3.json
resources.teleport.dev/teleportloginrule_v1.json
resources.teleport.dev/teleportoidcconnector_v3.json
resources.teleport.dev/teleportoktaimportrule_v1.json
resources.teleport.dev/teleportprovisiontoken_v2.json
resources.teleport.dev/teleportrole_v5.json
resources.teleport.dev/teleportrole_v6.json
resources.teleport.dev/teleportsamlconnector_v2.json
resources.teleport.dev/teleportuser_v2.json

https://github.com/gravitational/teleport/tree/c02e89cc6f1511ec2111ff037c902b5bb1891656/integrations/operator/config/crd/bases https://github.com/gravitational/teleport/tree/c02e89cc6f1511ec2111ff037c902b5bb1891656/examples/chart/teleport-cluster/charts/teleport-operator/templates

Add the Teleport CRDs

---

volsync.backube/replicationdestination_v1alpha1.json
volsync.backube/replicationsource_v1alpha1.json

Volsync CRDs were missing some fields. Re-dumped the CRDs and added it here

fix: add missing volsync fields

---

dynatrace.com/dynakube_v1alpha1.json
dynatrace.com/dynakube_v1beta1.json
dynatrace.com/edgeconnect_v1alpha1.json

```sh
curl https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.14.2/kubernetes.yaml --location --silent | yq 'select(.kind == "CustomResourceDefinition")' > dynakube.yaml
```

add dynatrace resources

---

logstash.k8s.elastic.co/logstash_v1alpha1.json

Add Logstash CRD
- Based on lattest CRD fetched from official Elastic repo : https://github.com/elastic/cloud-on-k8s/blob/2.10/config/crds/v1/bases/logstash.k8s.elastic.co_logstashes.yaml
- Converted into JSON using Kubeconfom: https://github.com/yannh/kubeconform#customresourcedefinition-crd-support

Add logstash CRD 

---

operator.cluster.x-k8s.io/addonprovider_v1alpha2.json
operator.cluster.x-k8s.io/bootstrapprovider_v1alpha1.json
operator.cluster.x-k8s.io/bootstrapprovider_v1alpha2.json
operator.cluster.x-k8s.io/controlplaneprovider_v1alpha1.json
operator.cluster.x-k8s.io/controlplaneprovider_v1alpha2.json
operator.cluster.x-k8s.io/coreprovider_v1alpha1.json
operator.cluster.x-k8s.io/coreprovider_v1alpha2.json
operator.cluster.x-k8s.io/infrastructureprovider_v1alpha1.json
operator.cluster.x-k8s.io/infrastructureprovider_v1alpha2.json
operator.cluster.x-k8s.io/ipamprovider_v1alpha2.json

Add schemas for [ClusterAPI Operator](https://github.com/kubernetes-sigs/cluster-api-operator) [CRDs v0.8.1](https://github.com/kubernetes-sigs/cluster-api-operator/tree/v0.8.1/config/crd/bases).

feat: add operator.cluster.x-k8s.io

---

postgresql.cnpg.io/cluster_v1.json

reference: [cluster_v1](https://github.com/cloudnative-pg/cloudnative-pg/blob/e8be9b5b093c4317626f586b1edfa6a2bdd47964/config/crd/bases/postgresql.cnpg.io_clusters.yaml#L3114-L3119)

feat(postgresql.cnpg.io): add `priorityClassName` property in `cluster_v1`

---

aadpodidentity.k8s.io/azureassignedidentity_v1.json
aadpodidentity.k8s.io/azureidentity_v1.json
aadpodidentity.k8s.io/azureidentitybinding_v1.json
aadpodidentity.k8s.io/azurepodidentityexception_v1.json

created with `./Utilities/crd-extractor.sh`
Link to CRDs: [https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/crds/crd.yaml](https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/crds/crd.yaml)

Add addpodidentity.k8s.io schemas

---

druid.apache.org/druid_v1alpha1.json

#281 
Reference: https://github.com/datainfrahq/druid-operator/tree/v1.2.3/config/crd/bases

feat: add apache druid crd v1.2.3

---

openebs.io/blockdevice_v1alpha1.json
openebs.io/blockdeviceclaim_v1alpha1.json
openebs.io/diskpool_v1beta1.json

created with `./Utilities/crd-extractor.sh`
Link to [CRDs](https://github.com/openebs/charts/tree/main/charts/openebs/crds)

Add openebs.io schemas

---

mysql.presslabs.org/mysqlbackup_v1alpha1.json
mysql.presslabs.org/mysqlbackup_v2.json
mysql.presslabs.org/mysqlcluster_v1alpha1.json
mysql.presslabs.org/mysqldatabase_v1alpha1.json
mysql.presslabs.org/mysqluser_v1alpha1.json

Adds the [Bitpoke MySQL Operator](https://github.com/bitpoke/mysql-operator) CRDs.

Add CRDs for Bitpoke MySQL Operator

---

monitoring.coreos.com/scrapeconfig_v1alpha1.json

I'm getting error when trying to validate my template using azureSDConfigs.

fix(monitoring.coreos.com/scrapeconfig_v1alpha1): missing azureSDConfigs

---

autopilot.k0sproject.io/controlnode_v1beta2.json
autopilot.k0sproject.io/plan_v1beta2.json
autopilot.k0sproject.io/updateconfig_v1beta2.json
dex.coreos.com/authcode_v1.json
dex.coreos.com/authrequest_v1.json
dex.coreos.com/connector_v1.json
dex.coreos.com/devicerequest_v1.json
dex.coreos.com/devicetoken_v1.json
dex.coreos.com/oauth2client_v1.json
dex.coreos.com/offlinesessions_v1.json
dex.coreos.com/password_v1.json
dex.coreos.com/refreshtoken_v1.json
dex.coreos.com/signingkey_v1.json
grafana.integreatly.org/grafana_v1beta1.json
grafana.integreatly.org/grafanadashboard_v1beta1.json
grafana.integreatly.org/grafanadatasource_v1beta1.json
grafana.integreatly.org/grafanafolder_v1beta1.json
helm.k0sproject.io/chart_v1beta1.json

Fixes #284 
I am not sure if its worth adding Dex CRD since they are just used by dex internally, but why not? It shouldn't harm.

Add CRD for k0s, dex and Grafana Operator

---

mysql.oracle.com/innodbcluster_v2.json
mysql.oracle.com/mysqlbackup_v2.json

Support mysql innodb-cluster operator CRD.
See:
* https://github.com/mysql/mysql-operator
* https://dev.mysql.com/doc/mysql-operator/en/mysql-operator-properties.html

feat: add innodbcluster CRDs

---

serving.kserve.io/clusterservingruntime_v1alpha1.json
serving.kserve.io/inferencegraph_v1alpha1.json
serving.kserve.io/inferenceservice_v1beta1.json
serving.kserve.io/servingruntime_v1alpha1.json
serving.kserve.io/trainedmodel_v1alpha1.json

This PR aims to add CRDs for [KServe](https://github.com/kserve/kserve/blob/master/config/crd/minimal/kustomization.yaml) using the crd-extractor.sh tool.

Add CRDs for KServe

---

config.gatekeeper.sh/config_v1alpha1.json
expansion.gatekeeper.sh/expansiontemplate_v1alpha1.json
expansion.gatekeeper.sh/expansiontemplate_v1beta1.json
externaldata.gatekeeper.sh/provider_v1alpha1.json
externaldata.gatekeeper.sh/provider_v1beta1.json
mutations.gatekeeper.sh/assign_v1.json
mutations.gatekeeper.sh/assign_v1alpha1.json
mutations.gatekeeper.sh/assign_v1beta1.json
mutations.gatekeeper.sh/assignimage_v1alpha1.json
mutations.gatekeeper.sh/assignmetadata_v1.json
mutations.gatekeeper.sh/assignmetadata_v1alpha1.json
mutations.gatekeeper.sh/assignmetadata_v1beta1.json
mutations.gatekeeper.sh/modifyset_v1.json
mutations.gatekeeper.sh/modifyset_v1alpha1.json
mutations.gatekeeper.sh/modifyset_v1beta1.json
status.gatekeeper.sh/constraintpodstatus_v1beta1.json
status.gatekeeper.sh/constrainttemplatepodstatus_v1beta1.json
status.gatekeeper.sh/expansiontemplatepodstatus_v1beta1.json
status.gatekeeper.sh/mutatorpodstatus_v1beta1.json
syncset.gatekeeper.sh/syncset_v1alpha1.json
templates.gatekeeper.sh/constrainttemplate_v1.json
templates.gatekeeper.sh/constrainttemplate_v1alpha1.json
templates.gatekeeper.sh/constrainttemplate_v1beta1.json

For reference, see https://github.com/open-policy-agent/gatekeeper/tree/v3.16.3/charts/gatekeeper/crds

update OPA Gatekeeper CRDs to current v3.16.3

---

external-secrets.io/clusterexternalsecret_v1beta1.json
external-secrets.io/clustersecretstore_v1alpha1.json
external-secrets.io/clustersecretstore_v1beta1.json
external-secrets.io/externalsecret_v1alpha1.json
external-secrets.io/externalsecret_v1beta1.json
external-secrets.io/pushsecret_v1alpha1.json
external-secrets.io/secretstore_v1alpha1.json
external-secrets.io/secretstore_v1beta1.json

Extracted via crd-extractor script

Adding updated External Secrets schemas

---

velero.io/backup_v1.json
velero.io/backuprepository_v1.json
velero.io/backupstoragelocation_v1.json
velero.io/datadownload_v2alpha1.json
velero.io/dataupload_v2alpha1.json
velero.io/deletebackuprequest_v1.json
velero.io/downloadrequest_v1.json
velero.io/podvolumebackup_v1.json
velero.io/podvolumerestore_v1.json
velero.io/restore_v1.json
velero.io/schedule_v1.json
velero.io/serverstatusrequest_v1.json
velero.io/volumesnapshotlocation_v1.json

```
VELERO_CHART_VERSION="velero-7.1.0"; cd velero.io; 
git clone git@github.com:vmware-tanzu/helm-charts.git velero-helm-charts; cd velero-helm-charts/; git switch --detach "${VELERO_CHART_VERSION}"; cd ..;
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py && chmod 755 openapi2jsonschema.py; 
find velero-helm-charts -wholename '*/crds/*.yaml' -exec python3 openapi2jsonschema.py {} \; && rm -f openapi2jsonschema.py; rm -rf velero-helm-charts/;
```

update velero CRDs (v1.14.0)

---

cert-manager.k8s.cloudflare.com/originissuer_v1.json

Generated using:
```bash
python3 /dev/stdin $(
curl -s https://api.github.com/repos/cloudflare/origin-ca-issuer/git/trees/v0.8.0\?recursive\=1 | \
jq -r '.tree[] | select(.path | startswith("deploy/crds/")) | "https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/v0.8.0/" + .path' | \
tr '\n' ' '
) | \
xargs -I {} sh -c 'mkdir -p $(dirname $(echo {} | sed "s|__|/|")) && mv {} $(echo {} | sed "s|__|/|")'
```

Add Cloudflare Origin CA Issuer CRDs (v0.8.0)

---

mongodbcommunity.mongodb.com/mongodbcommunity_v1.json

Source: https://github.com/mongodb/helm-charts/blob/512a25c0eb9b582851c3240f084d49b2977c090d/charts/community-operator-crds/templates/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
Alternate source: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
The schema was generated using the `crd-extractor.sh` tool.

feat: add mongodbcommunity crds

---

kyverno.io/admissionreport_v1alpha2.json
kyverno.io/admissionreport_v2.json
kyverno.io/backgroundscanreport_v1alpha2.json
kyverno.io/backgroundscanreport_v2.json
kyverno.io/cleanuppolicy_v2.json
kyverno.io/cleanuppolicy_v2alpha1.json
kyverno.io/cleanuppolicy_v2beta1.json
kyverno.io/clusteradmissionreport_v1alpha2.json
kyverno.io/clusteradmissionreport_v2.json
kyverno.io/clusterbackgroundscanreport_v1alpha2.json
kyverno.io/clusterbackgroundscanreport_v2.json
kyverno.io/clustercleanuppolicy_v2.json
kyverno.io/clustercleanuppolicy_v2alpha1.json
kyverno.io/clustercleanuppolicy_v2beta1.json
kyverno.io/clusterpolicy_v1.json
kyverno.io/clusterpolicy_v2beta1.json
kyverno.io/clusterpolicyreport_v1alpha2.json
kyverno.io/policy_v1.json
kyverno.io/policy_v2beta1.json
kyverno.io/policyexception_v2.json
kyverno.io/policyexception_v2alpha1.json
kyverno.io/policyexception_v2beta1.json
kyverno.io/policyreport_v1alpha2.json
kyverno.io/updaterequest_v1beta1.json
kyverno.io/updaterequest_v2.json

Used the CRD Extractor after a new, clean install of v1.12.4

Update Kyverno CRDs to current v1.12.4

---

keda.sh/cloudeventsource_v1alpha1.json
keda.sh/clustertriggerauthentication_v1alpha1.json
keda.sh/scaledjob_v1alpha1.json
keda.sh/scaledobject_v1alpha1.json
keda.sh/triggerauthentication_v1alpha1.json

This is my first contribution here!
I used the file [keda-2.14.0-crds.yaml](https://github.com/kedacore/keda/releases/download/v2.14.0/keda-2.14.0-crds.yaml) that is distributed on the [latest release v2.14.0](https://github.com/kedacore/keda/releases/tag/v2.14.0) and ran it through the CRD Extractor.
Hope that's enough :)

update keda.sh CRDs to v2.14.0

---

infrastructure.cluster.x-k8s.io/azureasomanagedcluster_v1alpha1.json
infrastructure.cluster.x-k8s.io/azureasomanagedclustertemplate_v1alpha1.json
infrastructure.cluster.x-k8s.io/azureasomanagedcontrolplane_v1alpha1.json
infrastructure.cluster.x-k8s.io/azureasomanagedcontrolplanetemplate_v1alpha1.json
infrastructure.cluster.x-k8s.io/azureasomanagedmachinepool_v1alpha1.json
infrastructure.cluster.x-k8s.io/azureasomanagedmachinepooltemplate_v1alpha1.json
infrastructure.cluster.x-k8s.io/azurecluster_v1beta1.json
infrastructure.cluster.x-k8s.io/azureclusteridentity_v1beta1.json
infrastructure.cluster.x-k8s.io/azureclustertemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremachine_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremachinepool_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremachinepoolmachine_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremachinetemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedcluster_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedclustertemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedcontrolplane_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedcontrolplanetemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedmachinepool_v1beta1.json
infrastructure.cluster.x-k8s.io/azuremanagedmachinepooltemplate_v1beta1.json

Generated with
```
git clone https://github.com/kubernetes-sigs/cluster-api-provider-azure.git --depth 1 --branch v1.16.0 && \
kubectl kustomize cluster-api-provider-azure/config/crd/ > crd.yaml && \
rm -rf cluster-api-provider-azure
```
relates to https://github.com/datreeio/CRDs-catalog/issues/357

Update and add cluster api azure CRD

---

clustersecret.io/clustersecret_v1.json

CRD Link: https://github.com/zakkg3/ClusterSecret/blob/master/charts/cluster-secret/crds/clustersecret-crd.yaml
The maintainer suggests either installing with Helm, which is the linked CRD, or by applying the `./yaml` directory from a cloned copy of their repo: https://github.com/zakkg3/ClusterSecret/blob/master/yaml/01_crd.yaml

Add clustersecret.io CRD

---

operator.victoriametrics.com/vmagent_v1beta1.json
operator.victoriametrics.com/vmalert_v1beta1.json
operator.victoriametrics.com/vmalertmanager_v1beta1.json
operator.victoriametrics.com/vmalertmanagerconfig_v1beta1.json
operator.victoriametrics.com/vmauth_v1beta1.json
operator.victoriametrics.com/vmcluster_v1beta1.json
operator.victoriametrics.com/vmnodescrape_v1beta1.json
operator.victoriametrics.com/vmpodscrape_v1beta1.json
operator.victoriametrics.com/vmprobe_v1beta1.json
operator.victoriametrics.com/vmrule_v1beta1.json
operator.victoriametrics.com/vmscrapeconfig_v1beta1.json
operator.victoriametrics.com/vmservicescrape_v1beta1.json
operator.victoriametrics.com/vmsingle_v1beta1.json
operator.victoriametrics.com/vmstaticscrape_v1beta1.json
operator.victoriametrics.com/vmuser_v1beta1.json

```shell
VMOPERATOR_VERSION="v0.46.4"
cd operator.victoriametrics.com
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
python3 openapi2jsonschema.py https://github.com/VictoriaMetrics/operator/releases/download/${VMOPERATOR_VERSION}/crd.yaml
rm openapi2jsonschema.py
```

Update victoriametrics CRDs (v0.46.4)

---

postgresql.cnpg.io/backup_v1.json
postgresql.cnpg.io/cluster_v1.json
postgresql.cnpg.io/clusterimagecatalog_v1.json
postgresql.cnpg.io/imagecatalog_v1.json
postgresql.cnpg.io/pooler_v1.json
postgresql.cnpg.io/scheduledbackup_v1.json

Updated cloudnative-pg schema for version 1.23
This would resolve #337.

Updated CNPG crd for 1.23

---

networking.istio.io/destinationrule_v1.json
networking.istio.io/gateway_v1.json
networking.istio.io/serviceentry_v1.json
networking.istio.io/sidecar_v1.json
networking.istio.io/virtualservice_v1.json
networking.istio.io/workloadentry_v1.json
networking.istio.io/workloadgroup_v1.json

Adds Istio 1.22 CRDs to the catalog

Catalog v1 networking.istio.io crds

---

elbv2.k8s.aws/ingressclassparams_v1beta1.json
elbv2.k8s.aws/targetgroupbinding_v1beta1.json

per https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.8.1/helm/aws-load-balancer-controller/crds/crds.yaml

elbv2.k8s.aws updates

---

ps.percona.com/perconaservermysql_v1alpha1.json
ps.percona.com/perconaservermysqlbackup_v1alpha1.json
ps.percona.com/perconaservermysqlrestore_v1alpha1.json

Hi! Not so long ago, Percona uploaded an update of its CRDs to [this repository](https://github.com/percona/percona-helm-charts/blob/main/charts/ps-operator/crds/crd.yaml). I have converted them to JSON, my resources were validated without any problems. Please update these CRDs in your repo.

Updated percona mysql CRDs

---

karpenter.k8s.aws/ec2nodeclass_v1.json
karpenter.sh/nodeclaim_v1.json
karpenter.sh/nodepool_v1.json

Karpenter V1 has been released: https://github.com/aws/karpenter-provider-aws/releases/tag/v1.0.0
CRDs: https://github.com/aws/karpenter-provider-aws/tree/main/pkg/apis/crds

Add karpenter v1 CRDs

---

isindir.github.com/sopssecret_v1alpha1.json
isindir.github.com/sopssecret_v1alpha2.json
isindir.github.com/sopssecret_v1alpha3.json

Upstream project: https://github.com/isindir/sops-secrets-operator

add SopsSecret resource

---

datadoghq.com/datadogagent_v2alpha1.json
datadoghq.com/datadogmetric_v1alpha1.json
datadoghq.com/datadogmonitor_v1alpha1.json
datadoghq.com/datadogpodautoscaler_v1alpha1.json

Release: https://github.com/DataDog/helm-charts/releases/tag/datadog-crds-2.0.0
CRDs: https://github.com/DataDog/helm-charts/tree/datadog-crds-2.0.0/crds

Update datadoghq.com crds to 2.0.0

---

snapscheduler.backube/snapshotschedule_v1.json

CRD source : https://github.com/backube/snapscheduler/tree/master/config/crd/bases
add snapscheduler crd

add snapschedule crd

---

app.redislabs.com/redisenterprisecluster_v1.json
app.redislabs.com/redisenterprisecluster_v1alpha1.json
app.redislabs.com/redisenterprisedatabase_v1alpha1.json

```bash
rm -rf app.redislabs.com && mkdir -p app.redislabs.com && pushd app.redislabs.com && \
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py && \
python openapi2jsonschema.py \
https://github.com/RedisLabs/certified-operators-redis/raw/main/operators/redis-enterprise-operator-cert/v6.2.10-34/manifests/rec_crd.yaml \
https://github.com/RedisLabs/certified-operators-redis/raw/main/operators/redis-enterprise-operator-cert/v6.2.10-34/manifests/redb_crd.yaml && \
rm openapi2jsonschema.py && popd
```
CRDs: https://github.com/RedisLabs/certified-operators-redis/tree/main/operators/redis-enterprise-operator-cert/v6.2.10-34/manifests

feat: add app.redislabs.com redis enterprise operator CRDs

---

appcat.vshn.io/objectbucket_v1.json
appcat.vshn.io/xobjectbucket_v1.json
exoscale.appcat.vshn.io/exoscalekafka_v1.json
exoscale.appcat.vshn.io/exoscalemysql_v1.json
exoscale.appcat.vshn.io/exoscaleopensearch_v1.json
exoscale.appcat.vshn.io/exoscalepostgresql_v1.json
exoscale.appcat.vshn.io/exoscaleredis_v1.json
vshn.appcat.vshn.io/compositemariadbinstance_v1.json
vshn.appcat.vshn.io/compositeredisinstance_v1.json
vshn.appcat.vshn.io/vshnkeycloak_v1.json
vshn.appcat.vshn.io/vshnmariadb_v1.json
vshn.appcat.vshn.io/vshnminio_v1.json
vshn.appcat.vshn.io/vshnnextcloud_v1.json
vshn.appcat.vshn.io/vshnpostgresql_v1.json
vshn.appcat.vshn.io/vshnredis_v1.json
vshn.appcat.vshn.io/xvshnkeycloak_v1.json
vshn.appcat.vshn.io/xvshnmariadb_v1.json
vshn.appcat.vshn.io/xvshnminio_v1.json
vshn.appcat.vshn.io/xvshnnextcloud_v1.json
vshn.appcat.vshn.io/xvshnpostgresql_v1.json
vshn.appcat.vshn.io/xvshnredis_v1.json

Source: https://github.com/vshn/appcat/tree/master/crds
Generated using `openapi2jsonschema.py`

Add appcat.vshn.io resources

---

cloudflare-operator.io/account_v1.json
cloudflare-operator.io/dnsrecord_v1.json
cloudflare-operator.io/ip_v1.json
cloudflare-operator.io/zone_v1.json

Sources: https://github.com/containeroo/cloudflare-operator/tree/master/config/crd/bases
Generated with `crd-extractor.sh`

Add cloudflare-operator.io resources

---

argoproj.io/analysisrun_v1alpha1.json
argoproj.io/analysistemplate_v1alpha1.json
argoproj.io/clusteranalysistemplate_v1alpha1.json
argoproj.io/experiment_v1alpha1.json
argoproj.io/rollout_v1alpha1.json

Update argo-rollouts to v1.7.2

---

logging.openshift.io/clusterlogforwarder_v1.json

Added azureMonitor in the cluster log forwarder output type in logging.openshift.io schema

Added azureMonitor in the cluster log forwarder output type in logging.openshift.io schema

---

grafana.integreatly.org/grafanadashboard_v1beta1.json
grafana.integreatly.org/grafanafolder_v1beta1.json

From https://github.com/grafana/grafana-operator/releases/tag/v5.15.0.

conf(grafana.integreatly.org): Update to support new properties

---

external-secrets.io/clusterexternalsecret_v1beta1.json
external-secrets.io/clustersecretstore_v1beta1.json
external-secrets.io/externalsecret_v1alpha1.json
external-secrets.io/externalsecret_v1beta1.json
external-secrets.io/pushsecret_v1alpha1.json
external-secrets.io/secretstore_v1beta1.json
generators.external-secrets.io/acraccesstoken_v1alpha1.json
generators.external-secrets.io/uuid_v1alpha1.json
generators.external-secrets.io/vaultdynamicsecret_v1alpha1.json

```sh
python3 /dev/stdin https://raw.githubusercontent.com/external-secrets/external-secrets/refs/tags/v0.10.5/deploy/crds/bundle.yaml | \
xargs -I {} sh -c 'f=$0; mkdir -p $(dirname $(echo $f | sed "s|__|/|")) && mv $f $(echo $f | sed "s|__|/|")' '{}'
```

External Secrets CRDs (v0.10.5)

---

flink.apache.org/flinkdeployment_v1beta1.json
flink.apache.org/flinksessionjob_v1beta1.json
flink.apache.org/flinkstatesnapshot_v1beta1.json

https://nightlies.apache.org/flink/flink-docs-release-1.20/release-notes/flink-1.20/

feat: add flink 1.20

---

gateway.envoyproxy.io/backend_v1alpha1.json
gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
gateway.envoyproxy.io/envoypatchpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyproxy_v1alpha1.json
gateway.envoyproxy.io/httproutefilter_v1alpha1.json
gateway.envoyproxy.io/securitypolicy_v1alpha1.json

Latest CRds for Envoy Gateway, extracted with `crd-extractor.sh`. Repo with CRDs: https://github.com/envoyproxy/gateway/tree/main

Add Envoy Gateway CRDs

---

infrastructure.cluster.x-k8s.io/gcpcluster_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpclustertemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpmachine_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpmachinetemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpmanagedcluster_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpmanagedcontrolplane_v1beta1.json
infrastructure.cluster.x-k8s.io/gcpmanagedmachinepool_v1beta1.json

```
$ git clone https://github.com/kubernetes-sigs/cluster-api-provider-gcp.git --depth 1 --branch main && \
kubectl kustomize cluster-api-provider-gcp/config/crd/ > crd.yaml && \
rm -rf cluster-api-provider-gcp
```

Update cluster api GCP CRD

---

traefik.io/ingressroute_v1alpha1.json
traefik.io/ingressroutetcp_v1alpha1.json
traefik.io/ingressrouteudp_v1alpha1.json
traefik.io/middleware_v1alpha1.json
traefik.io/middlewaretcp_v1alpha1.json
traefik.io/serverstransport_v1alpha1.json
traefik.io/serverstransporttcp_v1alpha1.json
traefik.io/tlsoption_v1alpha1.json
traefik.io/tlsstore_v1alpha1.json
traefik.io/traefikservice_v1alpha1.json

Signed-off-by: AvivGuiser <aviv.guiser@placer.ai>

update traefik crd

---

core.strimzi.io/strimzipodset_v1beta2.json

Signed-off-by: AvivGuiser <aviv.guiser@placer.ai>
CRD source: https://github.com/strimzi/strimzi-kafka-operator/tree/main/helm-charts/helm3/strimzi-kafka-operator/crds

add core.strimzi.io

---

linkerd.io/serviceprofile_v1alpha1.json
linkerd.io/serviceprofile_v1alpha2.json
policy.linkerd.io/authorizationpolicy_v1alpha1.json
policy.linkerd.io/httproute_v1.json
policy.linkerd.io/httproute_v1alpha1.json
policy.linkerd.io/httproute_v1beta1.json
policy.linkerd.io/httproute_v1beta2.json
policy.linkerd.io/httproute_v1beta3.json
policy.linkerd.io/meshtlsauthentication_v1alpha1.json
policy.linkerd.io/networkauthentication_v1alpha1.json
policy.linkerd.io/server_v1alpha1.json
policy.linkerd.io/server_v1beta1.json
policy.linkerd.io/serverauthorization_v1alpha1.json
policy.linkerd.io/serverauthorization_v1beta1.json

Signed-off-by: AvivGuiser <aviv.guiser@placer.ai>
CRD source https://github.com/linkerd/linkerd2/tree/main/charts/linkerd-crds

add linkerd crd

---

telemetry.istio.io/telemetry_v1.json

Adding telemetry.istio.io V1 schema

add telemetry.istio.io/v1

---

chisel-operator.io/exitnode_v1.json
chisel-operator.io/exitnodeprovisioner_v1.json

adding crds for chisel operator[^1]
[^1]: https://github.com/FyraLabs/chisel-operator

feat(chisel-operator.io): add chisel-operator

---

ceph.rook.io/cephblockpool_v1.json
ceph.rook.io/cephblockpoolradosnamespace_v1.json
ceph.rook.io/cephbucketnotification_v1.json
ceph.rook.io/cephbuckettopic_v1.json
ceph.rook.io/cephclient_v1.json
ceph.rook.io/cephcluster_v1.json
ceph.rook.io/cephcosidriver_v1.json
ceph.rook.io/cephfilesystem_v1.json
ceph.rook.io/cephfilesystemmirror_v1.json
ceph.rook.io/cephfilesystemsubvolumegroup_v1.json
ceph.rook.io/cephnfs_v1.json
ceph.rook.io/cephobjectrealm_v1.json
ceph.rook.io/cephobjectstore_v1.json
ceph.rook.io/cephobjectstoreuser_v1.json
ceph.rook.io/cephobjectzone_v1.json
ceph.rook.io/cephobjectzonegroup_v1.json
ceph.rook.io/cephrbdmirror_v1.json

feat(rook.ceph.io): add rook

---

k8s.mariadb.com/backup_v1alpha1.json
k8s.mariadb.com/connection_v1alpha1.json
k8s.mariadb.com/database_v1alpha1.json
k8s.mariadb.com/grant_v1alpha1.json
k8s.mariadb.com/mariadb_v1alpha1.json
k8s.mariadb.com/maxscale_v1alpha1.json
k8s.mariadb.com/restore_v1alpha1.json
k8s.mariadb.com/sqljob_v1alpha1.json
k8s.mariadb.com/user_v1alpha1.json

Source: https://github.com/mariadb-operator/mariadb-operator/tree/main/config/crd/bases

Add mariadb-operator CRDs

---

flagger.app/canary_v1beta1.json

CRD source: https://github.com/fluxcd/flagger/blob/main/charts/flagger/crds/crd.yaml

feat: update canaries.flagger.app crd

---

helm.toolkit.fluxcd.io/helmrelease_v2.json
source.toolkit.fluxcd.io/bucket_v1.json
source.toolkit.fluxcd.io/gitrepository_v1.json

Updated from fluxcd 2.3.0 to 2.4.0.

fluxcd 2.4.0 schema changes

---

apps.gitlab.com/gitlab_v1beta1.json

Extracted with the CRD extractor tools

feat: add apps.gitlab.com

---

psmdb.percona.com/perconaservermongodb_v1.json
psmdb.percona.com/perconaservermongodbbackup_v1.json
psmdb.percona.com/perconaservermongodbrestore_v1.json

Source of CRDs: https://github.com/percona/percona-helm-charts/blob/main/charts/psmdb-operator/crds/crd.yaml

Update Percona MongoDB CRDs

---

acme.cert-manager.io/challenge_v1.json
acme.cert-manager.io/order_v1.json
cert-manager.io/certificate_v1.json
cert-manager.io/certificaterequest_v1.json
cert-manager.io/clusterissuer_v1.json
cert-manager.io/issuer_v1.json

Update cert-manager.io crds using helm chart v1.16.2

---

k8s.mariadb.com/backup_v1alpha1.json
k8s.mariadb.com/connection_v1alpha1.json
k8s.mariadb.com/mariadb_v1alpha1.json
k8s.mariadb.com/maxscale_v1alpha1.json
k8s.mariadb.com/restore_v1alpha1.json
k8s.mariadb.com/sqljob_v1alpha1.json
k8s.mariadb.com/user_v1alpha1.json

https://github.com/mariadb-operator/mariadb-operator

Update mariadb-operator CRD to 0.37.1

---

datadoghq.com/datadogagent_v2alpha1.json
datadoghq.com/datadogmonitor_v1alpha1.json

Release: https://github.com/DataDog/helm-charts/releases/tag/datadog-crds-2.3.0
CRDs: https://github.com/DataDog/helm-charts/tree/datadog-crds-2.3.0/crds
-------

Update datadog-crds to 2.3.0

---

cloudflare-operator.io/account_v1.json
cloudflare-operator.io/dnsrecord_v1.json
cloudflare-operator.io/ip_v1.json
cloudflare-operator.io/zone_v1.json

Release: https://github.com/containeroo/cloudflare-operator/releases/tag/v1.4.0
CRDs: https://github.com/containeroo/cloudflare-operator/tree/master/config/crd/bases
---

Update cloudflare-operator.io resources

---

grafana.integreatly.org/grafana_v1beta1.json
grafana.integreatly.org/grafanaalertrulegroup_v1beta1.json
grafana.integreatly.org/grafanadashboard_v1beta1.json
grafana.integreatly.org/grafanadatasource_v1beta1.json
grafana.integreatly.org/grafanafolder_v1beta1.json
grafana.integreatly.org/grafananotificationpolicy_v1beta1.json

Release: https://github.com/grafana/grafana-operator/releases/tag/v5.15.0
CRDs: https://github.com/grafana/grafana-operator/tree/v5.15.0/deploy/helm/grafana-operator/crds

Update grafana crds to 5.15

---

kueue.x-k8s.io/admissioncheck_v1beta1.json
kueue.x-k8s.io/clusterqueue_v1beta1.json
kueue.x-k8s.io/cohort_v1alpha1.json
kueue.x-k8s.io/localqueue_v1beta1.json
kueue.x-k8s.io/multikueuecluster_v1beta1.json
kueue.x-k8s.io/multikueueconfig_v1beta1.json
kueue.x-k8s.io/provisioningrequestconfig_v1beta1.json
kueue.x-k8s.io/resourceflavor_v1beta1.json
kueue.x-k8s.io/topology_v1alpha1.json
kueue.x-k8s.io/workload_v1beta1.json
kueue.x-k8s.io/workloadpriorityclass_v1beta1.json

Adds CRDs for the latest version of [Kueue](https://kueue.sigs.k8s.io/). These CRDs are defined in the manifest [here](https://github.com/kubernetes-sigs/kueue/releases/download/v0.10.1/manifests.yaml)

Add kueue CRDs

---

job.min.io/miniojob_v1alpha1.json
minio.min.io/tenant_v2.json

Update minio CRDs

---

temporal.io/temporalcluster_v1beta1.json
temporal.io/temporalclusterclient_v1beta1.json
temporal.io/temporalnamespace_v1beta1.json
temporal.io/temporalschedule_v1beta1.json
temporal.io/temporalworkerprocess_v1beta1.json

Add Temporal.io CRDs

---

postgresql.cnpg.io/cluster_v3.json

Update CNPG postgres

---

objectbucket.io/objectbucket_v1alpha1.json
objectbucket.io/objectbucketclaim_v1alpha1.json

Updated to match the latest [v1.16.3 release](https://github.com/rook/rook/releases/tag/v1.16.3)

Update Rook object storage CRDs

---

gateway.networking.k8s.io/backendlbpolicy_v1alpha2.json
gateway.networking.k8s.io/backendtlspolicy_v1alpha3.json
gateway.networking.k8s.io/gateway_v1.json
gateway.networking.k8s.io/gateway_v1beta1.json
gateway.networking.k8s.io/gatewayclass_v1.json
gateway.networking.k8s.io/gatewayclass_v1beta1.json
gateway.networking.k8s.io/grpcroute_v1.json
gateway.networking.k8s.io/httproute_v1.json
gateway.networking.k8s.io/httproute_v1beta1.json
gateway.networking.k8s.io/tcproute_v1alpha2.json
gateway.networking.k8s.io/tlsroute_v1alpha2.json
gateway.networking.k8s.io/udproute_v1alpha2.json

Update Gateway API CRDs

---

policy.cert-manager.io/certificaterequestpolicy_v1alpha1.json

Add CRDs for [cert-manager approver-policy](https://github.com/cert-manager/approver-policy)

Add CRDs for cert-manager approver-policy

---

groupsnapshot.storage.k8s.io/volumegroupsnapshot_v1beta1.json
groupsnapshot.storage.k8s.io/volumegroupsnapshotclass_v1beta1.json
groupsnapshot.storage.k8s.io/volumegroupsnapshotcontent_v1beta1.json

Add Volume Snapshotter snapshot group CRDs

---

monitoring.coreos.com/alertmanager_v1.json
monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
monitoring.coreos.com/podmonitor_v1.json
monitoring.coreos.com/probe_v1.json
monitoring.coreos.com/prometheus_v1.json
monitoring.coreos.com/prometheusagent_v1alpha1.json
monitoring.coreos.com/prometheusrule_v1.json
monitoring.coreos.com/scrapeconfig_v1alpha1.json
monitoring.coreos.com/servicemonitor_v1.json
monitoring.coreos.com/thanosruler_v1.json

I used:
```
~/github.com/yannh/kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/jsonnet/prometheus-operator/alertmanagerconfigs-crd.json 
~/github.com/yannh/kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/jsonnet/prometheus-operator/alertmanagers-crd.json
~/github.com/yannh/kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/jsonnet/prometheus-operator/podmonitors-crd.json
~/github.com/yannh/kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/jsonnet/prometheus-operato …
```

Update monitoring.coreos.com CRDs

---

k8s.keycloak.org/keycloak_v2alpha1.json
k8s.keycloak.org/keycloakrealmimport_v2alpha1.json

Source of CRD is https://github.com/keycloak/keycloak-k8s-resources

add keycloak CRDs

---

dragonflydb.io/dragonfly_v1alpha1.json

Updated to latest v1.1.10 release

Update Dragonfly Operator CRDs

---

monitoring.coreos.com/alertmanager_v1.json
monitoring.coreos.com/prometheus_v1.json
monitoring.coreos.com/prometheusagent_v1alpha1.json
monitoring.coreos.com/thanosruler_v1.json

Add coreos.com (Prometheus).

---

traefik.io/ingressroute_v1alpha1.json
traefik.io/ingressroutetcp_v1alpha1.json
traefik.io/ingressrouteudp_v1alpha1.json
traefik.io/middleware_v1alpha1.json
traefik.io/middlewaretcp_v1alpha1.json
traefik.io/serverstransport_v1alpha1.json
traefik.io/serverstransporttcp_v1alpha1.json
traefik.io/tlsoption_v1alpha1.json
traefik.io/tlsstore_v1alpha1.json
traefik.io/traefikservice_v1alpha1.json

Update Traefik -> v3.3.4.

---

postgresql.cnpg.io/cluster_v1.json
postgresql.cnpg.io/pooler_v1.json

Add Postgresql Cluster and Pooler.

---

autoscaling.k8s.io/verticalpodautoscaler_v1.json
autoscaling.k8s.io/verticalpodautoscaler_v1beta2.json
autoscaling.k8s.io/verticalpodautoscalercheckpoint_v1.json
autoscaling.k8s.io/verticalpodautoscalercheckpoint_v1beta2.json

Update k8s autoscaling.

---

cilium.io/ciliumcidrgroup_v2alpha1.json
cilium.io/ciliumclusterwidenetworkpolicy_v2.json
cilium.io/ciliumegressgatewaypolicy_v2.json
cilium.io/ciliumendpoint_v2.json
cilium.io/ciliumexternalworkload_v2.json
cilium.io/ciliumidentity_v2.json
cilium.io/ciliuml2announcementpolicy_v2alpha1.json
cilium.io/ciliumloadbalancerippool_v2alpha1.json
cilium.io/ciliumnetworkpolicy_v2.json
cilium.io/ciliumnode_v2.json
cilium.io/ciliumnodeconfig_v2.json
cilium.io/ciliumnodeconfig_v2alpha1.json
cilium.io/ciliumpodippool_v2alpha1.json

Update Cilium -> v1.17.1.

---

kyverno.io/clusterpolicy_v2beta1.json
kyverno.io/policy_v2beta1.json

Update Kyverno using Helm Chart v3.3.7.

---

acme.cert-manager.io/challenge_v1.json
cert-manager.io/certificate_v1.json
cert-manager.io/clusterissuer_v1.json
cert-manager.io/issuer_v1.json

Update CertMAnager -> v1.17.1.

---

aquasecurity.github.io/clustercompliancereport_v1alpha1.json
aquasecurity.github.io/clusterconfigauditreport_v1alpha1.json
aquasecurity.github.io/clusterinfraassessmentreport_v1alpha1.json
aquasecurity.github.io/clusterrbacassessmentreport_v1alpha1.json
aquasecurity.github.io/clustersbomreport_v1alpha1.json
aquasecurity.github.io/clustervulnerabilityreport_v1alpha1.json
aquasecurity.github.io/configauditreport_v1alpha1.json
aquasecurity.github.io/exposedsecretreport_v1alpha1.json
aquasecurity.github.io/infraassessmentreport_v1alpha1.json
aquasecurity.github.io/rbacassessmentreport_v1alpha1.json
aquasecurity.github.io/sbomreport_v1alpha1.json
aquasecurity.github.io/vulnerabilityreport_v1alpha1.json

Added Trivy from Helm Chart v0.26.1.

---

authentication.concierge.pinniped.dev/jwtauthenticator_v1alpha1.json
authentication.concierge.pinniped.dev/webhookauthenticator_v1alpha1.json
config.concierge.pinniped.dev/credentialissuer_v1alpha1.json
config.supervisor.pinniped.dev/federationdomain_v1alpha1.json
config.supervisor.pinniped.dev/oidcclient_v1alpha1.json
idp.supervisor.pinniped.dev/activedirectoryidentityprovider_v1alpha1.json
idp.supervisor.pinniped.dev/githubidentityprovider_v1alpha1.json
idp.supervisor.pinniped.dev/ldapidentityprovider_v1alpha1.json
idp.supervisor.pinniped.dev/oidcidentityprovider_v1alpha1.json

Add Pinniped using Helm Chart v2.4.10.

---

external-secrets.io/clusterexternalsecret_v1beta1.json
external-secrets.io/clusterpushsecret_v1alpha1.json
external-secrets.io/clustersecretstore_v1beta1.json
external-secrets.io/pushsecret_v1alpha1.json
external-secrets.io/secretstore_v1beta1.json
generators.external-secrets.io/acraccesstoken_v1alpha1.json
generators.external-secrets.io/clustergenerator_v1alpha1.json
generators.external-secrets.io/grafana_v1alpha1.json
generators.external-secrets.io/vaultdynamicsecret_v1alpha1.json

chore: upgrade external secrets crds to v0.15.0

---

apps.jfrog.com/secretrotator_v1alpha1.json

Operator found here https://github.com/jfrog/jfrog-registry-operator

Adding Jfrog operator secret rotator crd

---

cilium.io/ciliumclusterwideenvoyconfig_v2.json
cilium.io/ciliumenvoyconfig_v2.json

cilium: Update Cilium Envoy CRDs from Cilium 1.17

---

cilium.io/ciliumbgpadvertisement_v2alpha1.json
cilium.io/ciliumbgpclusterconfig_v2alpha1.json
cilium.io/ciliumbgpnodeconfig_v2alpha1.json
cilium.io/ciliumbgpnodeconfigoverride_v2alpha1.json
cilium.io/ciliumbgppeerconfig_v2alpha1.json
cilium.io/ciliumbgppeeringpolicy_v2alpha1.json

cilium: Add bgp v2 CRDs from Cilum 1.17

---

apps.emqx.io/emqx_v2alpha1.json
apps.emqx.io/emqx_v2beta1.json
apps.emqx.io/emqxbroker_v1beta3.json
apps.emqx.io/emqxbroker_v1beta4.json
apps.emqx.io/emqxenterprise_v1beta3.json
apps.emqx.io/emqxenterprise_v1beta4.json
apps.emqx.io/emqxplugin_v1beta3.json
apps.emqx.io/emqxplugin_v1beta4.json
apps.emqx.io/rebalance_v1beta4.json
apps.emqx.io/rebalance_v2beta1.json

https://github.com/emqx/emqx-operator/releases/tag/2.2.28

emqx: Update to 2.2.28

---

operator.cluster.x-k8s.io/addonprovider_v1alpha2.json
operator.cluster.x-k8s.io/bootstrapprovider_v1alpha1.json
operator.cluster.x-k8s.io/bootstrapprovider_v1alpha2.json
operator.cluster.x-k8s.io/controlplaneprovider_v1alpha1.json
operator.cluster.x-k8s.io/controlplaneprovider_v1alpha2.json
operator.cluster.x-k8s.io/coreprovider_v1alpha1.json
operator.cluster.x-k8s.io/infrastructureprovider_v1alpha1.json
operator.cluster.x-k8s.io/infrastructureprovider_v1alpha2.json
operator.cluster.x-k8s.io/ipamprovider_v1alpha2.json
operator.cluster.x-k8s.io/runtimeextensionprovider_v1alpha2.json

https://github.com/kubernetes-sigs/cluster-api-operator/releases/tag/v0.17.1

clusterapi-operator: Update to 0.17.1

---

addons.cluster.x-k8s.io/clusterresourceset_v1alpha3.json
addons.cluster.x-k8s.io/clusterresourceset_v1alpha4.json
addons.cluster.x-k8s.io/clusterresourceset_v1beta1.json
addons.cluster.x-k8s.io/clusterresourcesetbinding_v1alpha3.json
addons.cluster.x-k8s.io/clusterresourcesetbinding_v1alpha4.json
addons.cluster.x-k8s.io/clusterresourcesetbinding_v1beta1.json
cluster.x-k8s.io/cluster_v1alpha3.json
cluster.x-k8s.io/cluster_v1alpha4.json
cluster.x-k8s.io/cluster_v1beta1.json
cluster.x-k8s.io/clusterclass_v1alpha4.json
cluster.x-k8s.io/clusterclass_v1beta1.json
cluster.x-k8s.io/machine_v1alpha3.json
cluster.x-k8s.io/machine_v1alpha4.json
cluster.x-k8s.io/machine_v1beta1.json
cluster.x-k8s.io/machinedeployment_v1alpha3.json
cluster.x-k8s.io/machinedeployment_v1alpha4.json
cluster.x-k8s.io/machinedeployment_v1beta1.json
cluster.x-k8s.io/machinedrainrule_v1beta1.json
cluster.x-k8s.io/machinehealthcheck_v1alpha3.json
cluster.x-k8s.io/machinehealthcheck_v1alpha4.json
cluster.x-k8s.io/machinehealthcheck_v1beta1.json
cluster.x-k8s.io/machinepool_v1alpha3.json
cluster.x-k8s.io/machinepool_v1alpha4.json
cluster.x-k8s.io/machinepool_v1beta1.json
cluster.x-k8s.io/machineset_v1alpha3.json
cluster.x-k8s.io/machineset_v1alpha4.json
cluster.x-k8s.io/machineset_v1beta1.json
clusterctl.cluster.x-k8s.io/provider_v1alpha3.json
runtime.cluster.x-k8s.io/extensionconfig_v1alpha1.json

https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.9.6

clusterapi: Update to 1.9.6

---

monitoring.coreos.com/alertmanager_v1.json
monitoring.coreos.com/prometheus_v1.json
monitoring.coreos.com/prometheusagent_v1alpha1.json
monitoring.coreos.com/scrapeconfig_v1alpha1.json
monitoring.coreos.com/thanosruler_v1.json

prometheus-operator: Update to 0.81.0

---

Utilities/auto-update-index.py
index.yaml

Minor bugfix + update of index file.

Auto update index: Delete empty groups.

---

bootstrap.cluster.x-k8s.io/talosconfig_v1alpha2.json
bootstrap.cluster.x-k8s.io/talosconfig_v1alpha3.json
bootstrap.cluster.x-k8s.io/talosconfigtemplate_v1alpha2.json
bootstrap.cluster.x-k8s.io/talosconfigtemplate_v1alpha3.json
controlplane.cluster.x-k8s.io/taloscontrolplane_v1alpha3.json

CRDs for latest version from:
https://github.com/siderolabs/cluster-api-bootstrap-provider-talos
https://github.com/siderolabs/cluster-api-control-plane-provider-talos

clusterapi: Add Talos providers CRDs

---

argoproj.io/application_v1alpha1.json
argoproj.io/applicationset_v1alpha1.json
argoproj.io/appproject_v1alpha1.json

```
kind create cluster && \
helm install argo-cd argo/argo-cd  -n argocd --create-namespace && \
./Utilities/crd-extractor.sh && \
cp -r $HOME/.datree/crdSchemas/ . && \
kind delete cluster && \
git commit -am "Updated argoproj.io crds to argocd v2.14.7"
```

Updated argoproj.io crds to argocd v2.14.7

---

certmanager.step.sm/stepclusterissuer_v1beta1.json
certmanager.step.sm/stepissuer_v1beta1.json

Added schemas for Smallstep certificate issuer:
https://github.com/smallstep/step-issuer
https://github.com/smallstep/helm-charts

add certmanager.step.sm

---

volsync.backube/replicationdestination_v1alpha1.json
volsync.backube/replicationsource_v1alpha1.json

Update volsync CRDs

---

notification.toolkit.fluxcd.io/alert_v1beta1.json
notification.toolkit.fluxcd.io/alert_v1beta2.json
notification.toolkit.fluxcd.io/alert_v1beta3.json
notification.toolkit.fluxcd.io/receiver_v1.json
notification.toolkit.fluxcd.io/receiver_v1beta1.json
notification.toolkit.fluxcd.io/receiver_v1beta2.json

Add FluxInstance and ResourceSetInputProvider to alert and receiver CRDs

---

azmonitoring.coreos.com/podmonitor_v1.json
azmonitoring.coreos.com/servicemonitor_v1.json

There is not a direct link to the CRD as it's published by Microsoft as a part of AKS

Add azmonitoring.coreos.com schema

---

pxc.percona.com/perconaxtradbcluster_v1.json
pxc.percona.com/perconaxtradbclusterbackup_v1.json
pxc.percona.com/perconaxtradbclusterrestore_v1.json

I didn't use the shell script, but extracted it with [openapi2jsonschema](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) script with the following command:
```
FILENAME_FORMAT='{kind}_{version}' openapi2jsonschema.py <(kubectl kustomize github.com/percona/percona-xtradb-cluster-operator/config/crd)
```

feat: update to latest pxc CRDs v1 version

---

tailscale.com/connector_v1alpha1.json
tailscale.com/dnsconfig_v1alpha1.json
tailscale.com/proxyclass_v1alpha1.json
tailscale.com/proxygroup_v1alpha1.json
tailscale.com/recorder_v1alpha1.json

CRDs generated from Tailscale Operator 1.78.3.

feat: add tailscale.com schemas

---

index.yaml
uds.dev/exemption_v1alpha1.json
uds.dev/package_v1alpha1.json

- These CRDs have been imported from [upstream UDS core v0.40.1](https://github.com/defenseunicorns/uds-core/tree/v0.40.1/schemas)
Closes #542

feat: add UDS CRDs

---

eks.services.k8s.aws/cluster_v1alpha1.json
elasticache.services.k8s.aws/snapshot_v1alpha1.json
elasticache.services.k8s.aws/user_v1alpha1.json
iam.services.k8s.aws/policy_v1alpha1.json
iam.services.k8s.aws/user_v1alpha1.json
memorydb.services.k8s.aws/cluster_v1alpha1.json
s3.services.k8s.aws/bucket_v1alpha1.json

fix the resources that were not synchronised.

more ACK resource

---

secrets.hashicorp.com/hcpauth_v1beta1.json
secrets.hashicorp.com/hcpvaultsecretsapp_v1beta1.json
secrets.hashicorp.com/secrettransformation_v1beta1.json
secrets.hashicorp.com/vaultauth_v1beta1.json
secrets.hashicorp.com/vaultauthglobal_v1beta1.json
secrets.hashicorp.com/vaultconnection_v1beta1.json
secrets.hashicorp.com/vaultdynamicsecret_v1beta1.json
secrets.hashicorp.com/vaultpkisecret_v1beta1.json
secrets.hashicorp.com/vaultstaticsecret_v1beta1.json

Pulled from https://github.com/hashicorp/vault-secrets-operator/tree/v0.10.0/chart/crds and converted with openapi2jsonschema.py.

Update secrets.hashicorp.com CRDs to v0.10.0

---

redis.redis.opstreelabs.in/redis_v1beta2.json
redis.redis.opstreelabs.in/rediscluster_v1beta2.json
redis.redis.opstreelabs.in/redisreplication_v1beta2.json
redis.redis.opstreelabs.in/redissentinel_v1beta2.json

Pulled from https://github.com/OT-CONTAINER-KIT/redis-operator/tree/v0.20.1/charts/redis-operator/crds and converted with openapi2jsonschema.py.

Add redis.redis.opstreelabs.in v0.20.1 CRDs

---

network.azure.upbound.io/firewallpolicyrulecollectiongroup_v1beta1.json

schema for firewall policy rcg

---

dynatrace.com/dynakube_v1beta2.json
dynatrace.com/dynakube_v1beta3.json
dynatrace.com/dynakube_v1beta4.json
dynatrace.com/edgeconnect_v1alpha2.json

- [x ] I have used the [CRD Extractor](https://github.com/datreeio/CRDs-catalog?tab=readme-ov-file#crd-extractor) tool to generate these CRDs

Add newer dynatrace CRDs

---

metal3.io/baremetalhost_v1alpha1.json
metal3.io/bmceventsubscription_v1alpha1.json
metal3.io/dataimage_v1alpha1.json
metal3.io/firmwareschema_v1alpha1.json
metal3.io/hardwaredata_v1alpha1.json
metal3.io/hostfirmwarecomponents_v1alpha1.json
metal3.io/hostfirmwaresettings_v1alpha1.json
metal3.io/hostupdatepolicy_v1alpha1.json
metal3.io/preprovisioningimage_v1alpha1.json

```
kind create cluster && \
kubectl create namespace baremetal-operator-system && \
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true --wait --wait-for-jobs && \
kustomize build https://github.com/metal3-io/baremetal-operator/config/default\?ref\=v0.10.1 | kubectl apply -f - && \
./Utilities/crd-extractor.sh && \
cp -r $HOME/.datree/crdSchemas/ . && \
kind delete cluster && \
git add -A metal3.io/* && \
git commit -m "Add metal3.io CRDs"
```

Add metal3.io CRDs

---

grafana.crossplane.io/providerconfig_v1beta1.json

Update ProviderConfig at Crossplane Grafana provider, last spec:
https://github.com/grafana/crossplane-provider-grafana/blob/main/package/crds/grafana.crossplane.io_providerconfigs.yaml

update grafana provider config with crossplane-provider-grafana

---

kargo.akuity.io/clusterpromotiontask_v1alpha1.json
kargo.akuity.io/freight_v1alpha1.json
kargo.akuity.io/project_v1alpha1.json
kargo.akuity.io/projectconfig_v1alpha1.json
kargo.akuity.io/promotion_v1alpha1.json
kargo.akuity.io/promotiontask_v1alpha1.json
kargo.akuity.io/stage_v1alpha1.json
kargo.akuity.io/warehouse_v1alpha1.json

chore: add kargo.akuity.io v1.5.0 CRDs

---

datadoghq.com/datadogagent_v2alpha1.json
datadoghq.com/datadogagentprofile_v1alpha1.json
datadoghq.com/datadogdashboard_v1alpha1.json
datadoghq.com/datadoggenericresource_v1alpha1.json
datadoghq.com/datadogmonitor_v1alpha1.json
datadoghq.com/datadogpodautoscaler_v1alpha2.json
datadoghq.com/datadogslo_v1alpha1.json

Release: https://github.com/DataDog/helm-charts/releases/tag/datadog-crds-2.7.0
CRDs: https://github.com/DataDog/helm-charts/tree/datadog-crds-2.7.0/crds

Update datadog crds to 2.7.0

---

operator.victoriametrics.com/vlogs_v1beta1.json
operator.victoriametrics.com/vmagent_v1beta1.json
operator.victoriametrics.com/vmalert_v1beta1.json
operator.victoriametrics.com/vmalertmanager_v1beta1.json
operator.victoriametrics.com/vmalertmanagerconfig_v1beta1.json
operator.victoriametrics.com/vmauth_v1beta1.json
operator.victoriametrics.com/vmcluster_v1beta1.json
operator.victoriametrics.com/vmnodescrape_v1beta1.json
operator.victoriametrics.com/vmpodscrape_v1beta1.json
operator.victoriametrics.com/vmprobe_v1beta1.json
operator.victoriametrics.com/vmscrapeconfig_v1beta1.json
operator.victoriametrics.com/vmservicescrape_v1beta1.json
operator.victoriametrics.com/vmsingle_v1beta1.json
operator.victoriametrics.com/vmstaticscrape_v1beta1.json
operator.victoriametrics.com/vmuser_v1beta1.json

```
VMOPERATOR_VERSION="v0.58.0"
cd operator.victoriametrics.com
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
python3 openapi2jsonschema.py https://github.com/VictoriaMetrics/operator/releases/download/${VMOPERATOR_VERSION}/crd.yaml
rm openapi2jsonschema.py
```

Update victoriametrics CRDs (v0.58.0)

---

wgpolicyk8s.io/clusterpolicyreport_v1alpha2.json
wgpolicyk8s.io/policyreport_v1alpha2.json

add wgpolicyk8s.io group

---

coroot.com/coroot_v1.json

add coroot.com group

---

v1.edp.epam.com/clusterkeycloak_v1alpha1.json
v1.edp.epam.com/clusterkeycloakrealm_v1alpha1.json
v1.edp.epam.com/keycloak_v1.json
v1.edp.epam.com/keycloakauthflow_v1.json
v1.edp.epam.com/keycloakclient_v1.json
v1.edp.epam.com/keycloakclientscope_v1.json
v1.edp.epam.com/keycloakrealm_v1.json
v1.edp.epam.com/keycloakrealmcomponent_v1.json
v1.edp.epam.com/keycloakrealmgroup_v1.json
v1.edp.epam.com/keycloakrealmidentityprovider_v1.json
v1.edp.epam.com/keycloakrealmrole_v1.json
v1.edp.epam.com/keycloakrealmrolebatch_v1.json
v1.edp.epam.com/keycloakrealmuser_v1.json

Add v1.edp.epam.com keycloak-operator CRDs

---

image.toolkit.fluxcd.io/imagepolicy_v1beta2.json
image.toolkit.fluxcd.io/imageupdateautomation_v1beta2.json
kustomize.toolkit.fluxcd.io/kustomization_v1.json
notification.toolkit.fluxcd.io/alert_v1beta1.json
notification.toolkit.fluxcd.io/alert_v1beta2.json
notification.toolkit.fluxcd.io/alert_v1beta3.json
notification.toolkit.fluxcd.io/provider_v1beta3.json
notification.toolkit.fluxcd.io/receiver_v1.json
notification.toolkit.fluxcd.io/receiver_v1beta1.json
notification.toolkit.fluxcd.io/receiver_v1beta2.json
source.toolkit.fluxcd.io/gitrepository_v1.json
source.toolkit.fluxcd.io/ocirepository_v1.json

Update fluxcd crds to reflect v2.6.1

---

kubescape.io/operatorcommand_v1alpha1.json
kubescape.io/runtimerulealertbinding_v1.json

Included CRDs:
- https://github.com/kubescape/helm-charts/blob/main/charts/dependency_chart/clustered-crds/crds/runtime-rule-binding.crd.yaml
- https://github.com/kubescape/helm-charts/blob/main/charts/dependency_chart/operatorcommand-crds/crds/operator-command.crd.yaml

Add kubescape.io group

---

gateway.envoyproxy.io/backend_v1alpha1.json
gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyproxy_v1alpha1.json
gateway.envoyproxy.io/httproutefilter_v1alpha1.json
gateway.envoyproxy.io/securitypolicy_v1alpha1.json

Extracted them from https://github.com/envoyproxy/gateway/tree/main/charts/gateway-helm/crds/generated

Update envoyproxy.gateway.io CRDs

---

acme.cert-manager.io/challenge_v1.json
acme.cert-manager.io/order_v1.json
cert-manager.io/certificate_v1.json
cert-manager.io/clusterissuer_v1.json
cert-manager.io/issuer_v1.json

Update cert-manager.io crds using helm chart v1.18.0

---

app.redislabs.com/redisenterpriseactiveactivedatabase_v1alpha1.json
app.redislabs.com/redisenterprisecluster_v1.json
app.redislabs.com/redisenterprisecluster_v1alpha1.json
app.redislabs.com/redisenterprisedatabase_v1alpha1.json
app.redislabs.com/redisenterpriseremotecluster_v1alpha1.json

Updated api.redislabs.com/RedisEnterprise operator CRDs to version 7.22.0 form RedHat Operator Hub.

Update api.redislabs.com/RedisEnterprise operator CRDs

---

clickhouse.altinity.com/clickhouseinstallation_v1.json
clickhouse.altinity.com/clickhouseinstallationtemplate_v1.json
clickhouse.altinity.com/clickhouseoperatorconfiguration_v1.json

add clickhouse.altinity.com/v1

---

external-secrets.io/clusterexternalsecret_v1.json
external-secrets.io/clusterexternalsecret_v1beta1.json
external-secrets.io/clusterpushsecret_v1alpha1.json
external-secrets.io/clustersecretstore_v1.json
external-secrets.io/clustersecretstore_v1beta1.json
external-secrets.io/externalsecret_v1.json
external-secrets.io/pushsecret_v1alpha1.json
external-secrets.io/secretstore_v1.json
external-secrets.io/secretstore_v1beta1.json
generators.external-secrets.io/clustergenerator_v1alpha1.json
generators.external-secrets.io/mfa_v1alpha1.json
generators.external-secrets.io/stssessiontoken_v1alpha1.json
generators.external-secrets.io/webhook_v1alpha1.json
index.yaml

Reference: https://github.com/external-secrets/external-secrets/tree/v0.18.2/config/crds/bases

Update external-secrets (v0.18.2)

---

clickhouse.altinity.com/clickhouseinstallation_v1.json
clickhouse.altinity.com/clickhouseinstallationtemplate_v1.json
clickhouse.altinity.com/clickhouseoperatorconfiguration_v1.json

update clickhouse.altinity.com to 0.25.2

---

keda.sh/clustertriggerauthentication_v1alpha1.json
keda.sh/scaledjob_v1alpha1.json
keda.sh/scaledobject_v1alpha1.json
keda.sh/triggerauthentication_v1alpha1.json

Update KEDA CRDs to latest version `v2.17.2`

---

fluxcd.controlplane.io/fluxinstance_v1.json

change fluxinstance schema. add provider to spec.sync.

---

gateway.envoyproxy.io/backend_v1alpha1.json
gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyproxy_v1alpha1.json
gateway.envoyproxy.io/securitypolicy_v1alpha1.json

New CRDS for envoy-gateway v1.5 https://github.com/envoyproxy/gateway/releases/tag/v1.5.0-rc.1

Update for envoy gateway 1.5 release

---

opentelemetry.io/opentelemetrycollector_v1beta1.json

Hello,
First thank you for your awesome work and this usefull repository. I'm using it with kubeconform.
But I found that the opentelemetrycollector_v1beta1.json schema seems not uptodate.
I offer you to update with this one, more recent and working for me.
I found it on this another github repository if you want to double check (or pull from this source) : https://github.com/Cust…omResourceDefinition/catalog
Please, can you accept and merge this PR.
Thank you in advance.

fix(opentelemetry): update opentelemetry v1beta1 

---

infrastructure.cluster.x-k8s.io/vspherecluster_v1beta1.json
infrastructure.cluster.x-k8s.io/vsphereclusteridentity_v1beta1.json
infrastructure.cluster.x-k8s.io/vsphereclustertemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheredeploymentzone_v1beta1.json
infrastructure.cluster.x-k8s.io/vspherefailuredomain_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheremachine_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheremachinetemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/vspherevm_v1beta1.json

add vsphere v1beta1 infrastructure to cluster api

---

infrastructure.cluster.x-k8s.io/vspherecluster_v1beta1.json
infrastructure.cluster.x-k8s.io/vsphereclusteridentity_v1beta1.json
infrastructure.cluster.x-k8s.io/vsphereclustertemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheredeploymentzone_v1beta1.json
infrastructure.cluster.x-k8s.io/vspherefailuredomain_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheremachine_v1beta1.json
infrastructure.cluster.x-k8s.io/vspheremachinetemplate_v1beta1.json
infrastructure.cluster.x-k8s.io/vspherevm_v1beta1.json

Updated Cluster API vsphere manifests

---

secretgenerator.mittwald.de/basicauth_v1alpha1.json
secretgenerator.mittwald.de/sshkeypair_v1alpha1.json
secretgenerator.mittwald.de/stringsecret_v1alpha1.json

https://github.com/mittwald/kubernetes-secret-generator/tree/v3.4.1/deploy/crds

feat: Add secretgenerator.mittwald.de CRDs (v3.4.1)

---

db.atlasgo.io/atlasmigration_v1alpha1.json
db.atlasgo.io/atlasschema_v1alpha1.json

This PR adds CRDs for https://atlasgo.io/

Add Atlas CRDs

---

monitoring.coreos.com/alertmanager_v1.json
monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
monitoring.coreos.com/podmonitor_v1.json
monitoring.coreos.com/probe_v1.json
monitoring.coreos.com/prometheus_v1.json
monitoring.coreos.com/prometheusagent_v1alpha1.json
monitoring.coreos.com/scrapeconfig_v1alpha1.json
monitoring.coreos.com/servicemonitor_v1.json
monitoring.coreos.com/thanosruler_v1.json

feat: update prometheus-operator to 0.85.0

---

ceph.rook.io/cephblockpool_v1.json
ceph.rook.io/cephblockpoolradosnamespace_v1.json
ceph.rook.io/cephbuckettopic_v1.json
ceph.rook.io/cephclient_v1.json
ceph.rook.io/cephcluster_v1.json
ceph.rook.io/cephfilesystem_v1.json
ceph.rook.io/cephfilesystemmirror_v1.json
ceph.rook.io/cephfilesystemsubvolumegroup_v1.json
ceph.rook.io/cephobjectrealm_v1.json
ceph.rook.io/cephobjectstore_v1.json
ceph.rook.io/cephobjectstoreuser_v1.json
ceph.rook.io/cephobjectzone_v1.json
ceph.rook.io/cephrbdmirror_v1.json

feat: Update ceph.rook.io to 1.18.2

---

argoproj.io/application_v1alpha1.json

feat: Update applications.argoproj.io to v3.1.6

---

kyverno.io/cleanuppolicy_v2.json
kyverno.io/cleanuppolicy_v2beta1.json
kyverno.io/clustercleanuppolicy_v2.json
kyverno.io/clustercleanuppolicy_v2beta1.json
kyverno.io/clusterpolicy_v1.json
kyverno.io/clusterpolicy_v2beta1.json
kyverno.io/globalcontextentry_v2alpha1.json
kyverno.io/policy_v1.json
kyverno.io/policy_v2beta1.json
kyverno.io/updaterequest_v2.json
policies.kyverno.io/deletingpolicy_v1alpha1.json
policies.kyverno.io/generatingpolicy_v1alpha1.json
policies.kyverno.io/imagevalidatingpolicy_v1alpha1.json
policies.kyverno.io/mutatingpolicy_v1alpha1.json
policies.kyverno.io/policyexception_v1alpha1.json
policies.kyverno.io/policyexception_v2.json
policies.kyverno.io/policyexception_v2beta1.json
policies.kyverno.io/validatingpolicy_v1alpha1.json
reports.kyverno.io/clusterephemeralreport_v1.json
reports.kyverno.io/ephemeralreport_v1.json

https://github.com/kyverno/kyverno/tree/main/config/crds

feat: Update kyverno.io to v1.15.2

---

gateway.envoyproxy.io/backendtrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
gateway.envoyproxy.io/envoyproxy_v1alpha1.json
gateway.envoyproxy.io/securitypolicy_v1alpha1.json

https://github.com/envoyproxy/gateway/releases/tag/v1.5.1

feat: update gateway.envoyproxy.io CRDs to v1.5.1

---

elbv2.k8s.aws/targetgroupbinding_v1alpha1.json
elbv2.k8s.aws/targetgroupbinding_v1beta1.json

Source: https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/v2.13.4/config/crd/bases

Update aws-load-balancer-controller CRDs

---

openreports.io/clusterreport_v1alpha1.json
openreports.io/report_v1alpha1.json

https://github.com/openreports/reports-api/tree/main/charts/openreports/templates

feat: Add openreports.io

---

talos.dev/serviceaccount_v1alpha1.json

https://github.com/siderolabs/talos/blob/main/internal/app/machined/pkg/controllers/k8s/internal/k8stemplates/testdata/talos-service-account-crd.yaml

feat: Add serviceaccounts.talos.dev

---

autoscaling.cast.ai/recommendations_v1.json

Cast AI is a platform that helps businesses optimize their Kubernetes clusters to reduce cloud costs, for more details check https://cast.ai

Add json schema for autoscaling.cast.ai
