datreeio/CRDs-catalog

autoscaling.k8s.io/verticalpodautoscaler_v1.json, autoscaling.k8s.io/verticalpodautoscaler_v1beta2.json, autoscaling.k8s.io/verticalpodautoscalercheckpoint_v1.json, autoscaling.k8s.io/verticalpodautoscalercheckpoint_v1beta2.json
This adds the CRDs for [VPA](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler). Generated using `crd-extractor.sh`
=> Add VerticalPodAutoscaler CRDs

secrets-store.csi.x-k8s.io/secretproviderclass_v1.json, secrets-store.csi.x-k8s.io/secretproviderclass_v1alpha1.json, secrets-store.csi.x-k8s.io/secretproviderclasspodstatus_v1.json, secrets-store.csi.x-k8s.io/secretproviderclasspodstatus_v1alpha1.json
Add [Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/) CRDs schemes.
Reference in kubernetes-sigs repo: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/config/crd/bases
Sorry but it is my first PR there and I'm not secure if needed update index.yaml file with k8s-sigs repo info.
=> feat: add Secrets Store CSI Driver CRDs

datadoghq.com/datadogmetric_v1alpha1.json
Add [DatadogMetrics CRD scheme](https://github.com/DataDog/helm-charts/blob/main/crds/datadoghq.com_datadogmetrics.yaml) of Datadog Monitoring.
I think this is the most used CRD to customize Datadog behaviors for example in HPAs. The other Datadog CRDs are defined by the official Datadog helm chart, and I don't think they are defined in application deployments.
=> feat: add datadogmetrics.datadoghq.com CRD

cloud.google.com/backendconfig_v1.json, cloud.google.com/backendconfig_v1beta1.json
These are under `cloud.google.com` instead of `networking.gke.io`
=> feat: add GCP backendconfig CRDs

external-secrets.io/clusterexternalsecret_v1beta1.json, external-secrets.io/clustersecretstore_v1beta1.json, external-secrets.io/externalsecret_v1beta1.json, external-secrets.io/secretstore_v1beta1.json, generators.external-secrets.io/acraccesstoken_v1alpha1.json, generators.external-secrets.io/ecrauthorizationtoken_v1alpha1.json, generators.external-secrets.io/fake_v1alpha1.json, generators.external-secrets.io/gcraccesstoken_v1alpha1.json, generators.external-secrets.io/password_v1alpha1.json
Updated `external-secrets.io` CRD schemas to v0.7.2, including new CRDs in the `generators.external-secrets.io` group.
See https://github.com/external-secrets/external-secrets/tree/v0.7.2/config/crds/bases.
=> feat: update External Secrets Operator CRDs to v0.7.2

enterprise.gloo.solo.io/authconfig_v1.json, gateway.solo.io/gateway_v1.json, gateway.solo.io/matchablehttpgateway_v1.json, gateway.solo.io/routeoption_v1.json, gateway.solo.io/routetable_v1.json, gateway.solo.io/virtualhostoption_v1.json, gateway.solo.io/virtualservice_v1.json, gloo.solo.io/proxy_v1.json, gloo.solo.io/settings_v1.json, gloo.solo.io/upstream_v1.json, gloo.solo.io/upstreamgroup_v1.json, graphql.gloo.solo.io/graphqlapi_v1beta1.json, ratelimit.solo.io/ratelimitconfig_v1alpha1.json
this PR adds CRDs from gloo (https://docs.solo.io/gloo-edge/latest/) , a k8s API gateway. 
CRDs extracted with CRD extractor from pristine docker desktop following the gloo yaml install
=> feature: add gloo CRDs

configuration.konghq.com/ingressclassparameters_v1alpha1.json, configuration.konghq.com/kongclusterplugin_v1.json, configuration.konghq.com/kongconsumer_v1.json, configuration.konghq.com/kongingress_v1.json, configuration.konghq.com/kongplugin_v1.json, configuration.konghq.com/tcpingress_v1beta1.json, configuration.konghq.com/udpingress_v1beta1.json
This PR adds kong CRDs (regular + enterprise ones)
https://konghq.com/
These schemas were created using crd-extractor.sh on a fresh minikube cluster after installing kong enterprise with the provided yaml file
=> feature: add kong API gateway CRDs

metallb.io/l2advertisement_v1beta1.json
New field introduced in metallb l2advetisement:
https://github.com/metallb/metallb/pull/1536
=> Add interfaces field in metallb.io l2advertisement_v1beta1.json

image.toolkit.fluxcd.io/imagerepository_v1beta2.json
Adds the newly released image.toolkit.fluxcd.io/v1beta2 CRDs. See the [release notes of upstream](https://fluxcd.io/flux/components/image/reflector-api/) for more info
=> Add imagerepository v1beta2 crds

Utilities/crd-extractor.sh
Instead of using pip3 which fails to find the yaml module if it is
installed globally via a different method (e.g. package manager) just
try to import it.
=> Check if the yaml module is importable

kyverno.io/clusterpolicy_v1.json, kyverno.io/clusterpolicy_v2beta1.json, kyverno.io/policy_v1.json, kyverno.io/policy_v2beta1.json
Hello! 
Kyverno recently deprecated `audit` and `enforce` validation failure actions, and added `Audit` and `Enforce` ([MR](https://github.com/kyverno/kyverno/pull/5152)). The old values are deprecated, and should be removed in 1.11. I have regenerated the schema against Kyverno v1.9.0 CRDs.
Let me know if you need any additional details. Thanks!
=> Update Kyverno CRDs

bmc.tinkerbell.org/job_v1alpha1.json, bmc.tinkerbell.org/machine_v1alpha1.json, bmc.tinkerbell.org/task_v1alpha1.json, tinkerbell.org/hardware_v1alpha1.json, tinkerbell.org/template_v1alpha1.json, tinkerbell.org/workflow_v1alpha1.json
This PR adds schemas for all CRs currently defined by the `tink` and `rufio` subprojects of [Tinkerbell](https://github.com/tinkerbell).
CRD sources:
```
$ kustomize build github.com/tinkerbell/tink/config/crd | yq -s '"crd_" + $index'
JSON schema written to hardware_v1alpha1.json
JSON schema written to template_v1alpha1.json
JSON schema written to workflow_v1alpha1.json
$ kustomize build github.com/tinkerbell/rufio/config/crd | yq -s '"crd_" + $index'
JSON schema written to job_v1alpha1.json
JSON schema written to machine_v1alpha1.json
JSON schema written to task_v1alpha1.json
```
=> Add Tinkerbell schemas

trust.cert-manager.io/bundle_v1alpha1.json
This PR adds schemas for all CRs currently defined by the [trust-manager](https://cert-manager.io/docs/projects/trust-manager/) subproject of cert-manager.
CRD sources:
```
$ curl -fsSL https://raw.githubusercontent.com/cert-manager/trust-manager/main/deploy/crds/trust.cert-manager.io_bundles.yaml -o crd.yml
JSON schema written to bundle_v1alpha1.json
```
=> Add cert-manager trust-manager schemas

infrastructure.cluster.x-k8s.io/tinkerbellcluster_v1beta1.json, infrastructure.cluster.x-k8s.io/tinkerbellmachine_v1beta1.json, infrastructure.cluster.x-k8s.io/tinkerbellmachinetemplate_v1beta1.json
This PR adds schemas for all CRs currently defined by the [Cluster API Provider Tinkerbell](https://github.com/tinkerbell/cluster-api-provider-tinkerbell).
CRD sources:
```
$ kubectl kustomize github.com/tinkerbell/cluster-api-provider-tinkerbell/config/crd | yq -s '"crd_" + $index'
JSON schema written to tinkerbellcluster_v1beta1.json
JSON schema written to tinkerbellmachine_v1beta1.json
JSON schema written to tinkerbellmachinetemplate_v1beta1.json
```
=> Add Cluster API Provider Tinkerbell schemas

infrastructure.cluster.x-k8s.io/nestedcluster_v1alpha4.json
This PR adds schemas for all CRs currently defined by the [Cluster API Provider Nested](https://github.com/kubernetes-sigs/cluster-api-provider-nested).
CRD sources:
```
$ kustomize build github.com/kubernetes-sigs/cluster-api-provider-nested/config/crd | yq -s '"crd_" + $index'
JSON schema written to nestedcluster_v1alpha4.json
```
=> Add Cluster API Provider Nested schemas

k6.io/k6_v1alpha1.json
This PR adds schemas for all CRs currently defined by Grafana Labs' [k6 Operator](https://github.com/grafana/k6-operator/).
CRD sources:
```
$ kustomize build github.com/grafana/k6-operator/config/crd | yq -s '"crd_" + $index'
JSON schema written to k6_v1alpha1.json
```
=> Add Grafana k6 operator schemas

infrastructure.cluster.x-k8s.io/gcpcluster_v1alpha2.json, infrastructure.cluster.x-k8s.io/gcpcluster_v1alpha3.json, infrastructure.cluster.x-k8s.io/gcpcluster_v1alpha4.json, infrastructure.cluster.x-k8s.io/gcpcluster_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpclustertemplate_v1alpha4.json, infrastructure.cluster.x-k8s.io/gcpclustertemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpmachine_v1alpha2.json, infrastructure.cluster.x-k8s.io/gcpmachine_v1alpha3.json, infrastructure.cluster.x-k8s.io/gcpmachine_v1alpha4.json, infrastructure.cluster.x-k8s.io/gcpmachine_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpmachinetemplate_v1alpha2.json, infrastructure.cluster.x-k8s.io/gcpmachinetemplate_v1alpha3.json, infrastructure.cluster.x-k8s.io/gcpmachinetemplate_v1alpha4.json, infrastructure.cluster.x-k8s.io/gcpmachinetemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpmanagedcluster_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpmanagedcontrolplane_v1beta1.json, infrastructure.cluster.x-k8s.io/gcpmanagedmachinepool_v1beta1.json
This PR adds schemas for all CRs currently defined by the [Cluster API Provider GCP](https://github.com/kubernetes-sigs/cluster-api-provider-gcp).
CRD sources:
```
$ kustomize build github.com/kubernetes-sigs/cluster-api-provider-gcp/config/crd | yq -s '"crd_" + $index'
JSON schema written to gcpcluster_v1alpha3.json
JSON schema written to gcpcluster_v1alpha4.json
JSON schema written to gcpcluster_v1beta1.json
JSON schema written to gcpclustertemplate_v1alpha4.json
JSON schema written to gcpclustertemplate_v1beta1.json
JSON schema written to gcpmachine_v1alpha3.json
JSON schema written to gcpmachine_v1alpha4.json
JSON schema written to gcpmachine_v1beta1.json
JSON schema written to gcpmachinetemplate_v1alpha3.json
JSON schema written to …
```
=> Add Cluster API Provider GCP schemas

karpenter.k8s.aws/awsnodetemplate_v1alpha1.json, karpenter.sh/provisioner_v1alpha5.json
I was attempting to validate some `karpenter` resources with valid provisioner schema. Saw that the CRD JSON schema in this repo was out of date, so I generated new ones with `crd-extractor.sh`
=> Update karpenter CRDs

security.istio.io/peerauthentication_v1beta1.json
The Istio PeerAuthentication actually has a different group than the networking.
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
```
https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#globally-enabling-istio-mutual-tls-in-strict-mode
I left the other file in networking in case that is a deprecated group from an earlier version.
=> fix: adding istio security peerauthentication

platform.confluent.io/clusterlink_v1beta1.json, platform.confluent.io/confluentrolebinding_v1beta1.json, platform.confluent.io/connect_v1beta1.json, platform.confluent.io/connector_v1beta1.json, platform.confluent.io/controlcenter_v1beta1.json, platform.confluent.io/kafka_v1beta1.json, platform.confluent.io/kafkarestclass_v1beta1.json, platform.confluent.io/kafkarestproxy_v1beta1.json, platform.confluent.io/kafkatopic_v1beta1.json, platform.confluent.io/ksqldb_v1beta1.json, platform.confluent.io/schema_v1beta1.json, platform.confluent.io/schemaexporter_v1beta1.json, platform.confluent.io/schemaregistry_v1beta1.json, platform.confluent.io/zookeeper_v1beta1.json
Schemas for [Confluent for Kubernetes](https://docs.confluent.io/operator/current). The CRDs were extracted from the [helm chart](https://packages.confluent.io/helm/confluent-for-kubernetes-0.581.55.tgz).
=> Add Confluent Operator schemas

apps.emqx.io/emqx_v2alpha1.json, apps.emqx.io/emqxbroker_v1beta3.json, apps.emqx.io/emqxbroker_v1beta4.json, apps.emqx.io/emqxenterprise_v1beta3.json, apps.emqx.io/emqxenterprise_v1beta4.json, apps.emqx.io/emqxplugin_v1beta3.json, apps.emqx.io/emqxplugin_v1beta4.json
When using Kubeconform the checks failed against emqx crd's. Using the CRD extractor from this repo I extracted them from my K8s cluster.
Upstream CRD's for reference: https://github.com/emqx/emqx-operator/tree/main/deploy/charts/emqx-operator/templates
=> Add emqx schemas

dapr.io/component_v1alpha1.json, dapr.io/configuration_v1alpha1.json, dapr.io/resiliency_v1alpha1.json, dapr.io/subscription_v1alpha1.json, dapr.io/subscription_v2alpha1.json
When using Kubeconform the checks failed against dapr crd's. Using the CRD extractor from this repo I extracted them from my K8s cluster.
Upstream CRD's for reference: https://github.com/dapr/dapr/tree/master/charts/dapr/crds
=> Add dapr schemas

databases.spotahome.com/redisfailover_v1.json
When using Kubeconform the checks failed against redisfailover crd. Using the CRD extractor from this repo I extracted them from my K8s cluster. 
Upstream CRD for reference: https://github.com/spotahome/redis-operator/blob/master/charts/redisoperator/crds/databases.spotahome.com_redisfailovers.yaml
=> Add redisfailover schema

operator.tigera.io/apiserver_v1.json, operator.tigera.io/imageset_v1.json, operator.tigera.io/installation_v1.json, operator.tigera.io/tigerastatus_v1.json
When using Kubeconform the checks failed against tigera-operator crd's. Using the CRD extractor from this repo I extracted them from my K8s cluster.
Upstream CRD's for reference: https://github.com/projectcalico/calico/tree/master/charts/tigera-operator/crds
=> Added tigera operator schemas

traefik.io/ingressroute_v1alpha1.json, traefik.io/ingressroutetcp_v1alpha1.json, traefik.io/ingressrouteudp_v1alpha1.json, traefik.io/middleware_v1alpha1.json, traefik.io/middlewaretcp_v1alpha1.json, traefik.io/serverstransport_v1alpha1.json, traefik.io/tlsoption_v1alpha1.json, traefik.io/tlsstore_v1alpha1.json, traefik.io/traefikservice_v1alpha1.json
Add noted on https://doc.traefik.io/traefik/v2.10/migration/v2/#kubernetes-crds:
> In v2.10, the Kubernetes CRDs API Group `traefik.containo.us` is deprecated, and its support will end starting with Traefik v3. Please use the API Group `traefik.io` instead.
This PR add the current `v1alpha1` CRDs published by Traefik under the new group name (but does not remove the old ones). Also worth noting `v1alpha1` will be replaced by `v1` in Traefik 3.x as mentioned in #119, but from their repo these CRD specs don't seem to be finalised yet.
=> add traefik CRDs under new group name

acid.zalan.do/operatorconfiguration_v1.json, acid.zalan.do/postgresql_v1.json, acid.zalan.do/postgresteam_v1.json
Added Zalando Postgres Operator Schemas.
Group: `acid.zalan.do`.
A list of CRDs:
- `OperatorConfiguration`
- `postgresql`
- `PostgresTeam`
Here is the commands I used to generate them:
```bash
python openapi2jsonschema.py https://github.com/zalando/postgres-operator/raw/master/charts/postgres-operator/crds/operatorconfigurations.yaml
python openapi2jsonschema.py https://github.com/zalando/postgres-operator/raw/master/charts/postgres-operator/crds/postgresqls.yaml
python openapi2jsonschema.py https://github.com/zalando/postgres-operator/raw/master/charts/postgres-operator/crds/postgresteams.yaml
```
Reference: <https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator/crds>
Source: <https://github.com/zalando/postgres-operator/tree/master>
=> [acid.zalan.do] Add Zalando Postgres Operator Schemas

dbaas.percona.com/databasecluster_v1.json, dbaas.percona.com/databaseclusterrestore_v1.json, dbaas.percona.com/databaseengine_v1.json
Added Percona DBaaS Operator Schemas.
Group: `dbaas.percona.com`.
A list of CRDs:
- `DatabaseClusterRestore` - `v1`
- `DatabaseCluster`  - `v1`
- `DatabaseEngine` - `v1`
Here is the commands I used to generate them:
```bash
python openapi2jsonschema.py https://raw.githubusercontent.com/percona/dbaas-operator/main/deploy/bundle.yaml
```
Reference: <https://raw.githubusercontent.com/percona/dbaas-operator/main/deploy/bundle.yaml>
Source: <https://github.com/percona/dbaas-operator>
=> [dbaas.percona.com] Add Percona DBaaS Operator Schemas

ps.percona.com/perconaservermysql_v1alpha1.json, ps.percona.com/perconaservermysqlbackup_v1alpha1.json, ps.percona.com/perconaservermysqlrestore_v1alpha1.json
Added Percona MySQL Operator Schemas.
Group: `ps.percona.com`.
A list of CRDs:
- `PerconaServerMySQLBackup` - `v1alpha1`
- `PerconaServerMySQLRestore` - `v1alpha1`
- `PerconaServerMySQL` - `v1alpha1`
Here is the commands I used to generate them:
```bash
python openapi2jsonschema.py https://raw.githubusercontent.com/percona/percona-server-mysql-operator/main/deploy/bundle.yaml
```
Reference: <https://raw.githubusercontent.com/percona/percona-server-mysql-operator/main/deploy/bundle.yaml>
Source: <https://github.com/percona/percona-server-mysql-operator>
=> [ps.percona.com] Add Percona MySQL Operator Schemas

postgresql.cnpg.io/backup_v1.json, postgresql.cnpg.io/cluster_v1.json, postgresql.cnpg.io/pooler_v1.json, postgresql.cnpg.io/scheduledbackup_v1.json
Add CloudnativePG CRDs
Group: `postgresql.cnpg.io`
List of CRDs:
* `Backup`
* `Cluster`
* `Pooler`
* `ScheduledBackup`
Here is the commands that I used to generate them:
```bash
python openapi2jsonschema.py https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_backups.yaml
python openapi2jsonschema.py https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml
python openapi2jsonschema.py https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_poolers.yaml
python openapi2jsonschema.py https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
```
Reference: …
=> [postgresql.cnpg.io] Add CloudNativePG CRDs

elbv2.k8s.aws/ingressclassparams_v1beta1.json, elbv2.k8s.aws/targetgroupbinding_v1alpha1.json, elbv2.k8s.aws/targetgroupbinding_v1beta1.json
This takes the CRDs from ALB controller v2.5.
The following example is based on the ALB controller documentation:
```shell
kubeconform -summary -output json -schema-location './elbv2.k8s.aws/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' - <<EOF
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
name: alb-internal
spec:
group:
name: my-cluster-alb-group
scheme: internal
inboundCIDRs: ['10.0.0.0/8']
tags:
- key: k8s.acme.org/managed-by
value: loadbalancer-controller
- key: k8s.acme.org/cluster-name
value: my-cluster
EOF
{
"resources": [],
"summary": {
"valid": 1,
"invalid": 0,
"errors": 0,
"skipped": 0
}
}
```
Comparing the same resource to the current version of the CRDs-catalog project:
```shell
kubeconform -summary -output json -schema-location default …
```
=> fix: update alb controller crds

cert-manager.io/clusterissuer_v1.json
I think there are more api updates for this version, but this resolves schema validation issues I have had with route53 dns resolver configuration: https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-clusterissuers.yaml#L371C41-L371C47
=> update cert manager clusterissuer

argoproj.io/application_v1alpha1.json, argoproj.io/applicationset_v1alpha1.json, argoproj.io/appproject_v1alpha1.json
Argo CD just did a release ([`v2.8.0`](https://github.com/argoproj/argo-cd/releases/tag/v2.8.0)) that added some major updates to their CRDs.
Thanks for maintaining this project!
=> update argoproj.io Argo CD schemas for 2.8.0 release

velero.io/backup_v1.json, velero.io/backuprepository_v1.json, velero.io/backupstoragelocation_v1.json, velero.io/deletebackuprequest_v1.json, velero.io/downloadrequest_v1.json, velero.io/podvolumebackup_v1.json, velero.io/podvolumerestore_v1.json, velero.io/restore_v1.json, velero.io/schedule_v1.json, velero.io/serverstatusrequest_v1.json, velero.io/volumesnapshotlocation_v1.json
This adds the following CRDs for Velero:
* backups
* backuprepositories
* backupstoragelocations
* deletebackuprequests
* downloadrequests
* podvolumebackups
* podvolumerestores
* restores
* schedules
* serverstatusrequests
* volumesnapshotlocations
The CRDs / schemas were extracted with:
```
cd velero.io/
git clone git@github.com:vmware-tanzu/helm-charts.git velero-helm-charts cd velero-helm-charts/ && git checkout velero-4.4.1 && cd .. find velero-helm-charts/ -wholename '*/crds/*.yaml' -exec python3 ../openapi2jsonschema.py {} \;
```
Closes https://github.com/datreeio/CRDs-catalog/issues/200
=> feat: add all velero.io CRDs

openshift/v4.11-strict/containerruntimeconfig_v1.json, openshift/v4.11-strict/kubeletconfig_v1.json, openshift/v4.11-strict/machineconfig_v1.json, openshift/v4.11-strict/machineconfigpool_v1.json
This commit adds the following CRDs for the
"machineconfiguration.openshift.io" group:
* ContainerRuntimeConfig
* KubeletConfig
* MachineConfig
* MachineConfigPool
The schemas were extracted with:
```
cd openshift/v4.11-strict/
git clone git@github.com:openshift/machine-config-operator.git
cd machine-config-operator/ && git checkout release-4.11 && cd ..
find machine-config-operator/ -wholename '*/install/*.crd.yaml' -exec python3 ../../openapi2jsonschema.py {} \;
```
=> feat: Add OpenShift Machine-Config-Operator CRDs

actions.summerwind.dev/horizontalrunnerautoscaler_v1alpha1.json, actions.summerwind.dev/runner_v1alpha1.json, actions.summerwind.dev/runnerdeployment_v1alpha1.json, actions.summerwind.dev/runnerreplicaset_v1alpha1.json, actions.summerwind.dev/runnerset_v1alpha1.json
The GitHub Actions Controller hasn't released in 3+ months but the master branch contains important updates to the CRDs, which are crucial to actually running the GitHub Actions Controller.
`dockerVarRunVolumeSizeLimit` was added that allows to increase the `/run` volume on self-hosted runners for Docker usage.
Would love to see it merged soon as my pipeline is failing that validates our resources.
=> chore: update actions.summerwind.dev to master branch state

cert-manager.io/issuer_v1.json
This will add `ingressClassName` to issuer schema, which will solve our validation schema.
JSON file was generated using [openapi2jsonschema.py script](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) from [cert-manager issuer CRD file](https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/crd-issuers.yaml)
=> Update cert-manager issuer schema

flink.apache.org/flinkdeployment_v1beta1.json, flink.apache.org/flinksessionjob_v1beta1.json
This commit adds the following CRDs for the
"flink.apache.org" group:
flinkdeployments.flink.apache.org     
flinksessionjobs.flink.apache.org
The schemas were extracted with:
(Summary)
- Passing YAML validation: 1/1
- Passing Kubernetes (1.24.0) schema validation: 1/1
- Passing policy check: 1/1
+-----------------------------------+----+
| Enabled rules in policy "Starter" | 34 |
| Configs tested against policy     | 1  |
| Total rules evaluated             | 34 |
| Total rules skipped               | 0  |
| Total rules failed                | 0  |
| Total rules passed                | 34 |
| See all rules in policy           |    |
+-----------------------------------+----+
[INFO] You're running Datree in offline mode%
=> feat: :sparkles: adding apache flink operators crds

logging.openshift.io/clusterlogforwarder_v1.json, logging.openshift.io/clusterlogging_v1.json
This commit adds the following CRDs in the "logging.openshift.io" group:
* ClusterLogForwarder
* ClusterLogging
The schemas were generated with the following commands:
```
git clone git@github.com:openshift/cluster-logging-operator.git
cd cluster-logging-operator/ && git checkout release-5.7 && cd ..
find cluster-logging-operator/ -wholename '*/config/crd/bases/*.yaml' -exec python3 ../openapi2jsonschema.py {} \;
```
Note that the "cluster-logging-operator" is no longer a core part of OpenShift (it's an optional addon).
This means it's release cadence is decoupled from OpenShift releases.
Hence I put these CRD schemas into `logging.openshift.io` instead of the existing `openshift.io`.
=> feat: add OpenShift Cluster Logging CRDs

argoproj.io/clusteranalysistemplate_v1alpha1.json
Updating argo's clusteranalysistemplate schema to be up to date with the latest version (as of Nov 29, 2023 that's commit [ebf1a3e](https://github.com/argoproj/argo-rollouts/commit/ebf1a3ed24ed08d04f034a13fd780b9771c69be4) of the [argo rollouts repo](https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/cluster-analysis-template-crd.yaml#L26).
Used [kubeconform's openapi2jsonschema script](https://github.com/yannh/kubeconform#customresourcedefinition-crd-support) to generate the schema:
```
$ python3 ./scripts/openapi2jsonschema.py https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/crds/cluster-analysis-template-crd.yaml
JSON schema written to clusteranalysistemplate_v1alpha1.json
```
I couldn't find any guidelines on contributing, but happy to …
=> fix: argoproj.io clusternanalysistemplate schema

argoproj.io/application_v1alpha1.json, argoproj.io/applicationset_v1alpha1.json
Argo CD had another major release v2.9 that added some changes to their CRDs. This PR incorporates all changes as of ([v2.9.3](https://github.com/argoproj/argo-cd/releases/tag/v2.9.3)) .
I've used the `crd-extractor.sh` to extract the CRDs from a clean k3d cluster.
Tested manually using `kubeconform` against custom resources that previously failed validation when linked against this repository.
=> update argoproj.io Argo CD schemas for 2.9.3 release

notification.toolkit.fluxcd.io/provider_v1beta2.json
Datadog is a supported provider for [this version](https://fluxcd.io/flux/components/notification/providers/#datadog)
=> include datadog in provider_v1beta2.json

kyverno.io/admissionreport_v1alpha2.json, kyverno.io/cleanuppolicy_v2beta1.json, kyverno.io/clusteradmissionreport_v1alpha2.json, kyverno.io/clustercleanuppolicy_v2beta1.json, kyverno.io/clusterpolicy_v1.json, kyverno.io/clusterpolicy_v2beta1.json, kyverno.io/policy_v1.json, kyverno.io/policy_v2beta1.json, kyverno.io/policyexception_v2beta1.json, kyverno.io/updaterequest_v1beta1.json
chore: update kyverno/v1 crd schemas as per v1.11.0 as they are missing some of the newly added objects.
=> chore: update kyverno/v1 crd schemas as per v1.11.0

argoproj.io/clusterworkflowtemplate_v1alpha1.json, argoproj.io/cronworkflow_v1alpha1.json, argoproj.io/workflow_v1alpha1.json, argoproj.io/workflowartifactgctask_v1alpha1.json, argoproj.io/workfloweventbinding_v1alpha1.json, argoproj.io/workflowtaskresult_v1alpha1.json, argoproj.io/workflowtaskset_v1alpha1.json, argoproj.io/workflowtemplate_v1alpha1.json
Hi, thank you for maintaining this repository...! This is really helpful to improve our productivity by validating configurations before deploying it.
I tried to update Argo Workflow CRDs to v3.5.4 using the following script.
```bash
set -eu
set -o pipefail
ARGO_WORKFLOW_VERSION='3.5.4'
KUBECONFORM_DIR=<PATH to kubeconform repository>
kinds=(
clusterworkflowtemplates
cronworkflows
workflowartifactgctasks
workfloweventbindings
workflows
workflowtaskresults
workflowtasksets
workflowtemplates
)
for kind in "${kinds[@]}"; do
python3 ${KUBECONFORM_DIR}/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/argoproj/argo-workflows/v${ARGO_WORKFLOW_VERSION}/manifests/base/crds/full/argoproj.io_${kind}.yaml
done
```
CRDs-catalog has an utility tool to extract CRDs from an existing …
=> Update Argo Workflow CRDs to v3.5.4

scylla.scylladb.com/nodeconfig_v1alpha1.json, scylla.scylladb.com/scyllacluster_v1.json, scylla.scylladb.com/scylladbmonitoring_v1alpha1.json, scylla.scylladb.com/scyllaoperatorconfig_v1alpha1.json
Add's the Scylla DB Operator CRDs extracted with the crd-extractor.sh utility.
See https://github.com/scylladb/scylla-operator for more information regarding the project.
=> feat: add Scylla DB Operator CRDs

operators.coreos.com/catalogsource_v1alpha1.json, operators.coreos.com/clusterserviceversion_v1alpha1.json, operators.coreos.com/installplan_v1alpha1.json, operators.coreos.com/olmconfig_v1.json, operators.coreos.com/operator_v1.json, operators.coreos.com/operatorcondition_v1.json, operators.coreos.com/operatorcondition_v2.json, operators.coreos.com/operatorgroup_v1.json, operators.coreos.com/operatorgroup_v1alpha2.json, operators.coreos.com/subscription_v1alpha1.json
The `operators.coreos.com` CRDs such as [Subscription](https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/subscription-operators-coreos-com-v1alpha1.html), [OperatorGroup](https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/operatorgroup-operators-coreos-com-v1.html), [Operator](https://docs.openshift.com/container-platform/4.14/rest_api/operatorhub_apis/operator-operators-coreos-com-v1.html) etc. are heavily used by the [Operator Framework](https://operatorframework.io/what/) (specifically the [OLM](https://olm.operatorframework.io/) in OpenShift).
The schemas were generated with:
```
git clone https://github.com/operator-framework/operator-lifecycle-manager.git
cd operator-lifecycle-manager && git checkout v0.26.0 && cd ..
mkdir …
```
=> feat: add OLM v1 CRDs (operators.coreos.com)

secrets.hashicorp.com/hcpvaultsecretsapp_v1beta1.json, secrets.hashicorp.com/secrettransformation_v1beta1.json, secrets.hashicorp.com/vaultauth_v1beta1.json, secrets.hashicorp.com/vaultdynamicsecret_v1beta1.json, secrets.hashicorp.com/vaultpkisecret_v1beta1.json, secrets.hashicorp.com/vaultstaticsecret_v1beta1.json
Pulled from https://github.com/hashicorp/vault-secrets-operator/tree/v0.5.2/chart/crds, converted with `openapi2jsonschema.py`.
Supersedes #283.
=> Update secrets.hashicorp.com CRDs to v0.5.2

monitoring.coreos.com/scrapeconfig_v1alpha1.json
https://github.com/datreeio/CRDs-catalog/pull/299 introduced azureSDConfigs into the schema but added an additional `}`. Afterwards the schema was not usable anymore. 
yaml-ls reports the following error when using the schema with 
`yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json`
`Unable to parse content from 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json': Parse error at offset 72328.`
=> fix: corrupted scrapeconfig_v1alpha1.json

helm.toolkit.fluxcd.io/helmrelease_v2.json, source.toolkit.fluxcd.io/helmrepository_v1.json
A new version of the Helm repository and Helm release is now available.
The document is: https://fluxcd.io/flux/components/helm/helmreleases/
=> Add helmrepository_v1 and helmrelease_v2 of FluxCD

operator.victoriametrics.com/vmrule_v1beta1.json
Support `keep_firing_for` field that Victoria Metrics supports.
[Commit](https://github.com/VictoriaMetrics/operator/commit/76acb80997672f041ac2f8f3fe63f6cece9f4cf1) adding `keep_firing_for`
=> feat: add keep_firing_for to vmrule

traefik.io/ingressroute_v1alpha1.json, traefik.io/ingressroutetcp_v1alpha1.json, traefik.io/ingressrouteudp_v1alpha1.json, traefik.io/middleware_v1alpha1.json, traefik.io/middlewaretcp_v1alpha1.json, traefik.io/serverstransport_v1alpha1.json, traefik.io/serverstransporttcp_v1alpha1.json, traefik.io/tlsoption_v1alpha1.json, traefik.io/tlsstore_v1alpha1.json, traefik.io/traefikservice_v1alpha1.json
Current Traefik CRDs are outdated and don't support the new `ipAllowList` Middleware type.
=> Update Traefik CRDs to Traefik v2.11

acid.zalan.do/operatorconfiguration_v1.json, acid.zalan.do/postgresql_v1.json
Identically as in #168, regenerated the Schemas for the Zalando Postgres Operator after the release of version 1.12.2: https://github.com/zalando/postgres-operator/releases/tag/v1.12.2
Reference: https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator/crds
Source: https://github.com/zalando/postgres-operator/tree/master
=>  [acid.zalan.do] Update Zalando Postgres Operator Schemas

cloudsql.cloud.google.com/authproxyworkload_v1.json
Generated using:
```bash
python3 /dev/stdin https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy-operator/v1.4.5/cloud-sql-proxy-operator.yaml | \
xargs -I {} sh -c 'mkdir -p $(dirname $(echo {} | sed "s|__|/|")) && mv {} $(echo {} | sed "s|__|/|")'
```
Source repo: https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator
=> Add GCP Cloud SQL Operator CRDs (v1.4.5)

karpenter.k8s.aws/ec2nodeclass_v1beta1.json, karpenter.sh/nodeclaim_v1beta1.json, karpenter.sh/nodepool_v1beta1.json
I started receiving error messages from `kubeconform` when using the `instanceProfile` field of Karpenter rather than the the `role` for the `EC2NodeClass` resource.  When looking up the actual [CRD definition](https://raw.githubusercontent.com/aws/karpenter/main/pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml), this should not be happening:
Role Definition:
```yaml
role:
description: |-
Role is the AWS identity that nodes use. This field is immutable.
This field is mutually exclusive from instanceProfile.
Marking this field as immutable avoids concerns around terminating managed instance profiles from running instances.
This field may be made mutable in the future, assuming the correct garbage collection and drift handling is implemented
for the old instance profiles on an update. …
```
=> Updating Karpenter v1beta1 Spec

kafka.strimzi.io/kafka_v1beta2.json, kafka.strimzi.io/kafkabridge_v1beta2.json, kafka.strimzi.io/kafkaconnect_v1beta2.json, kafka.strimzi.io/kafkaconnector_v1beta2.json, kafka.strimzi.io/kafkamirrormaker2_v1beta2.json, kafka.strimzi.io/kafkamirrormaker_v1beta2.json, kafka.strimzi.io/kafkanodepool_v1beta2.json, kafka.strimzi.io/kafkarebalance_v1beta2.json, kafka.strimzi.io/kafkatopic_v1alpha1.json, kafka.strimzi.io/kafkatopic_v1beta1.json, kafka.strimzi.io/kafkatopic_v1beta2.json, kafka.strimzi.io/kafkauser_v1alpha1.json, kafka.strimzi.io/kafkauser_v1beta1.json, kafka.strimzi.io/kafkauser_v1beta2.json, kafka.strimzi.io/strimzipodset_v1beta2.json
`KafkaNodePool` CRD was introduced as GA from Strimzi 0.41 and this changed the requirement fields of `Kafka` CRDs.
I also updated other CRDs related to Strimzi. Just in case, these updates are created by running CRD Extractor toward my cluster.
=> Update Strimzi/Kafka CRDs to Strimzi 0.41

external-secrets.io/clusterexternalsecret_v1beta1.json, external-secrets.io/clustersecretstore_v1alpha1.json, external-secrets.io/clustersecretstore_v1beta1.json, external-secrets.io/externalsecret_v1alpha1.json, external-secrets.io/externalsecret_v1beta1.json, external-secrets.io/pushsecret_v1alpha1.json, external-secrets.io/secretstore_v1alpha1.json, external-secrets.io/secretstore_v1beta1.json, generators.external-secrets.io/acraccesstoken_v1alpha1.json, generators.external-secrets.io/ecrauthorizationtoken_v1alpha1.json, generators.external-secrets.io/fake_v1alpha1.json, generators.external-secrets.io/gcraccesstoken_v1alpha1.json, generators.external-secrets.io/githubaccesstoken_v1alpha1.json, generators.external-secrets.io/password_v1alpha1.json, generators.external-secrets.io/vaultdynamicsecret_v1alpha1.json, generators.external-secrets.io/webhook_v1alpha1.json
```bash
python3 /dev/stdin https://raw.githubusercontent.com/external-secrets/external-secrets/v0.9.19/deploy/crds/bundle.yaml | \
xargs -I {} sh -c 'f=$0; mkdir -p $(dirname $(echo $f | sed "s|__|/|")) && mv $f $(echo $f | sed "s|__|/|")' '{}'
```
=> Update External Secrets CRDs (v0.9.19)

gateway.networking.k8s.io/gateway_v1.json, gateway.networking.k8s.io/gateway_v1beta1.json, gateway.networking.k8s.io/gatewayclass_v1.json, gateway.networking.k8s.io/gatewayclass_v1beta1.json, gateway.networking.k8s.io/grpcroute_v1.json, gateway.networking.k8s.io/grpcroute_v1alpha2.json, gateway.networking.k8s.io/httproute_v1.json, gateway.networking.k8s.io/httproute_v1beta1.json, gateway.networking.k8s.io/referencegrant_v1alpha2.json, gateway.networking.k8s.io/referencegrant_v1beta1.json
The CRDs were fetched using the CRD extractor tool after installing them from the standard channel like this ([docs](https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api) for reference):
```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
```
=> Add K8s Gateway API v1.1.0 standard channel CRDs.

dragonflydb.io/dragonfly_v1alpha1.json
[Dragonfly](https://www.dragonflydb.io/) is a drop-in Redis replacement, designed to meet the performance and efficiency requirements of modern cloud-based applications. 
This PR adds a Dragonfly instance schema to the catalog, extracted using the CRD extractor.
=> Add DragonflyDB.io Dragonfly schema

externaldns.k8s.io/dnsendpoint_v1alpha1.json
Generated schemas using [openapi2jsonschema.py](https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py) python script.
DNS endpoint was already present but for `externaldns.nginx.org` not [`externaldns.k8s.io`](https://github.com/kubernetes-sigs/external-dns)
```
✖ stdin: DNSEndpoint failed validation: design-token-proxy-dns could not find schema for DNSEndpoint
```
[Source](https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/charts/external-dns/crds/dnsendpoint.yaml) on master.
Hope this helps ! ✌️
=> chore(externaldns): add dnsendpoint schema v1alpha1

bootstrap.cluster.x-k8s.io/eksconfig_v1beta1.json, bootstrap.cluster.x-k8s.io/eksconfig_v1beta2.json, bootstrap.cluster.x-k8s.io/eksconfigtemplate_v1beta1.json, bootstrap.cluster.x-k8s.io/eksconfigtemplate_v1beta2.json, controlplane.cluster.x-k8s.io/awsmanagedcontrolplane_v1beta1.json, controlplane.cluster.x-k8s.io/awsmanagedcontrolplane_v1beta2.json, controlplane.cluster.x-k8s.io/rosacontrolplane_v1beta2.json, infrastructure.cluster.x-k8s.io/awscluster_v1beta1.json, infrastructure.cluster.x-k8s.io/awscluster_v1beta2.json, infrastructure.cluster.x-k8s.io/awsclustercontrolleridentity_v1beta1.json, infrastructure.cluster.x-k8s.io/awsclustercontrolleridentity_v1beta2.json, infrastructure.cluster.x-k8s.io/awsclusterroleidentity_v1beta1.json, infrastructure.cluster.x-k8s.io/awsclusterroleidentity_v1beta2.json, infrastructure.cluster.x-k8s.io/awsclusterstaticidentity_v1beta1.json, infrastructure.cluster.x-k8s.io/awsclusterstaticidentity_v1beta2.json, infrastructure.cluster.x-k8s.io/awsclustertemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/awsclustertemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/awsfargateprofile_v1beta1.json, infrastructure.cluster.x-k8s.io/awsfargateprofile_v1beta2.json, infrastructure.cluster.x-k8s.io/awsmachine_v1beta1.json, infrastructure.cluster.x-k8s.io/awsmachine_v1beta2.json, infrastructure.cluster.x-k8s.io/awsmachinepool_v1beta1.json, infrastructure.cluster.x-k8s.io/awsmachinepool_v1beta2.json, infrastructure.cluster.x-k8s.io/awsmachinetemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/awsmachinetemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/awsmanagedmachinepool_v1beta1.json, infrastructure.cluster.x-k8s.io/awsmanagedmachinepool_v1beta2.json, infrastructure.cluster.x-k8s.io/rosacluster_v1beta2.json, infrastructure.cluster.x-k8s.io/rosamachinepool_v1beta2.json
Generated with
```
git clone https://github.com/kubernetes-sigs/cluster-api-provider-aws.git --depth 1 --branch v2.6.1 && \
kubectl kustomize cluster-api-provider-aws/config/crd/ > crd.yaml && \
rm -rf cluster-api-provider-aws
```
previous one: https://github.com/datreeio/CRDs-catalog/pull/136
=> Update cluster api AWS CRD to 2.6.1

jetstream.nats.io/account_v1beta2.json, jetstream.nats.io/consumer_v1beta1.json, jetstream.nats.io/consumer_v1beta2.json, jetstream.nats.io/stream_v1beta1.json, jetstream.nats.io/stream_v1beta2.json, jetstream.nats.io/streamtemplate_v1beta1.json
https://github.com/datreeio/CRDs-catalog/issues/371
Adding NACK Crds. 
Location of the CRDs.
https://github.com/nats-io/nack/blob/main/deploy/crds.yml
Generated using Crds extractor script
=> Add Nack CRDs

pxc.percona.com/perconaxtradbcluster_v1.json, pxc.percona.com/perconaxtradbclusterbackup_v1.json, pxc.percona.com/perconaxtradbclusterrestore_v1.json
CRDs of [Percona Operator for MySQL based on Percona XtraDB Cluster](https://github.com/percona/percona-xtradb-cluster-operator) were updated since [last PR added it to this repo the previous year](https://github.com/datreeio/CRDs-catalog/pull/172)  
Reference: https://raw.githubusercontent.com/percona/percona-xtradb-cluster-operator/v1.15.0/deploy/bundle.yaml
=> feat: update pxc.percona.com v1 CRD

flink.apache.org/flinkdeployment_v1beta1.json, flink.apache.org/flinksessionjob_v1beta1.json
This update Flink CRDs to latest operator release 1.9
* [CRDs](https://github.com/apache/flink-kubernetes-operator/tree/release-1.9.0/helm/flink-kubernetes-operator/crds)
=> feat: upgrade flink crd to flink-kubernetes-operator 1.9

app.redislabs.com/redisenterpriseactiveactivedatabase_v1alpha1.json, app.redislabs.com/redisenterprisecluster_v1.json, app.redislabs.com/redisenterprisecluster_v1alpha1.json, app.redislabs.com/redisenterprisedatabase_v1alpha1.json, app.redislabs.com/redisenterpriseremotecluster_v1alpha1.json
Follow up to #383
When looking further, I realized that the manifest I was using was out of date. I've re-generated using the latest manifests: https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators/redis-enterprise-operator-cert/7.4.6-2.0/manifests
Redis enterprise operator is now maintained as part of the official redhat ecosystem certified operators.
```
rm -rf app.redislabs.com && mkdir -p app.redislabs.com && pushd app.redislabs.com && \
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py && \
python openapi2jsonschema.py \
https://github.com/redhat-openshift-ecosystem/certified-operators/raw/main/operators/redis-enterprise-operator-cert/7.4.6-2.0/manifests/reaadb_crd.yaml \ …
```
=> upgrade: app.redislabs.com to version 7.4.6-2.0

serving.kserve.io/clusterservingruntime_v1alpha1.json, serving.kserve.io/inferencegraph_v1alpha1.json, serving.kserve.io/inferenceservice_v1beta1.json, serving.kserve.io/servingruntime_v1alpha1.json, serving.kserve.io/trainedmodel_v1alpha1.json
This PR aims to update the Kserve [CRDs](https://github.com/kserve/kserve/tree/master/charts/kserve-crd/templates) from the latest version (v0.13.1) using the crd-extractor.sh tool.
- The priority field for the ClusterServingRuntime is missing, raising invalid validation such as:
`ClusterServingRuntime kserve-mlserver is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/supportedModelFormats/0' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/master/serving.kserve.io/clusterservingruntime_v1alpha1.json#/properties/spec/properties/supportedModelFormats/items/additionalProperties: additionalProperties 'priority' not allowed`
=> feat(kserve): update Kserve CRDs (v0.13.1)

argoproj.io/analysisrun_v1alpha1.json, argoproj.io/analysistemplate_v1alpha1.json, argoproj.io/clusteranalysistemplate_v1alpha1.json, argoproj.io/experiment_v1alpha1.json, argoproj.io/rollout_v1alpha1.json
I tried to update Argo Workflow CRDs to v3.5.4 using the following script.
```bash
set -eu
set -o pipefail
ARGO_ROLLOUTS_VERSION='1.6.6'
KUBECONFORM_DIR=<path to kubeconform>
kinds=(
analysis-run-crd
analysis-template-crd
cluster-analysis-template-crd
experiment-crd
kustomization
rollout-crd
)
for kind in "${kinds[@]}"; do
python3 ${KUBECONFORM_DIR}/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/argoproj/argo-rollouts/v${ARGO_ROLLOUTS_VERSION}/manifests/crds/${kind}.yaml
done
```
CRDs-catalog has an utility tool to extract CRDs from an existing cluster, named CRD Extractor. In most cases, we can use the tool to update CRDs. However I wasn't able to point it at a cluster due to networking issues.
Therefore, I directly used openapi2jsonchema.py in the kubeconform repository …
=> Update argo-rollouts to v1.6.6

acid.zalan.do/operatorconfiguration_v1.json, acid.zalan.do/postgresql_v1.json
Identically as in https://github.com/datreeio/CRDs-catalog/pull/336, regenerated the Schemas for the Zalando Postgres Operator after the release of version 1.13.0: https://github.com/zalando/postgres-operator/releases/tag/v1.13.0
Reference: https://github.com/zalando/postgres-operator/tree/master/charts/postgres-operator/crds
Source: https://github.com/zalando/postgres-operator/tree/master
=> chore: update postgres zalando schemas

external-secrets.io/clustersecretstore_v1beta1.json, external-secrets.io/secretstore_v1beta1.json
This PR adds the ability to choose namespaces using regex matching in the ClusterSecretStore and SecretStore resources. It introduces a new field called "namespaceRegexes" which accepts an array of regex patterns to match against namespaces. This feature provides more flexibility in selecting namespaces for processing ExternalSecrets.
According to the following PR in External Secrets: https://github.com/external-secrets/external-secrets/pull/2920
=> feat: Add support for namespace regex matching in ClusterSecretStore and SecretStore

fluentbit.fluent.io/clusterfilter_v1alpha2.json, fluentbit.fluent.io/clusterfluentbitconfig_v1alpha2.json, fluentbit.fluent.io/clusterinput_v1alpha2.json, fluentbit.fluent.io/clustermultilineparser_v1alpha2.json, fluentbit.fluent.io/clusteroutput_v1alpha2.json, fluentbit.fluent.io/clusterparser_v1alpha2.json, fluentbit.fluent.io/collector_v1alpha2.json, fluentbit.fluent.io/filter_v1alpha2.json, fluentbit.fluent.io/fluentbit_v1alpha2.json, fluentbit.fluent.io/fluentbitconfig_v1alpha2.json, fluentbit.fluent.io/multilineparser_v1alpha2.json, fluentbit.fluent.io/output_v1alpha2.json, fluentbit.fluent.io/parser_v1alpha2.json, fluentd.fluent.io/clusterfilter_v1alpha1.json, fluentd.fluent.io/clusterfilter_v1alpha2.json, fluentd.fluent.io/clusterfluentdconfig_v1alpha1.json, fluentd.fluent.io/clusterinput_v1alpha1.json, fluentd.fluent.io/clusterinput_v1alpha2.json, fluentd.fluent.io/clusteroutput_v1alpha1.json, fluentd.fluent.io/clusteroutput_v1alpha2.json, fluentd.fluent.io/filter_v1alpha1.json, fluentd.fluent.io/filter_v1alpha2.json, fluentd.fluent.io/fluentd_v1alpha1.json, fluentd.fluent.io/fluentdconfig_v1alpha1.json, fluentd.fluent.io/input_v1alpha1.json, fluentd.fluent.io/output_v1alpha1.json, fluentd.fluent.io/output_v1alpha2.json
This PR aims to introduce [fluent-operator](https://github.com/fluent/fluent-operator) [fluent-bit CRDs](https://github.com/fluent/fluent-operator/tree/master/charts/fluent-operator/charts/fluent-bit-crds/crds) and [fluentd CRDs](https://github.com/fluent/fluent-operator/tree/master/charts/fluent-operator/charts/fluentd-crds/crds) from the latest version (v3.2.0) using the following script:
```sh
#!/usr/bin/env bash
set -euo pipefail
cleanup_cmd="rm -rf ${PWD}/fluent-operator ${PWD}/openapi2jsonschema.py"
trap "rm -f $cleanup_cmd" 0            # EXIT
trap "rm -f $cleanup_cmd; exit 1" 2    # INT
trap "rm -f $cleanup_cmd; exit 1" 1 15 # HUP TERM
FLUENT_OPERATOR_VERSION=v3.2.0
curl -sO https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
mkdir -p …
```
=> feat: fluent-operator CRDs (v3.2.0)

argoproj.io/application_v1alpha1.json, argoproj.io/applicationset_v1alpha1.json
Add latest argo-cd application and applicationset CRDs for v2.10.4, which includes [templatePatch](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#template-patch) as a feature for ApplicationSets.
=> add latest argo-cd application and applicationset CRDs for v2.10.4

kyverno.io/cleanuppolicy_v2.json, kyverno.io/cleanuppolicy_v2beta1.json, kyverno.io/clustercleanuppolicy_v2.json, kyverno.io/clustercleanuppolicy_v2beta1.json, kyverno.io/clusterephemeralreport_v1.json, kyverno.io/clusterpolicy_v1.json, kyverno.io/clusterpolicy_v2beta1.json, kyverno.io/clusterpolicyreport_v1alpha2.json, kyverno.io/ephemeralreport_v1.json, kyverno.io/globalcontextentry_v2alpha1.json, kyverno.io/policy_v1.json, kyverno.io/policy_v2beta1.json, kyverno.io/policyexception_v2.json, kyverno.io/policyexception_v2beta1.json, kyverno.io/policyreport_v1alpha2.json, kyverno.io/updaterequest_v1beta1.json, kyverno.io/updaterequest_v2.json
Very similar to https://github.com/datreeio/CRDs-catalog/pull/338, updated the CRDs using
github.com/yannh/kubeconform/scripts/openapi2jsonschema.py against the templated CRDs from https://github.com/kyverno/kyverno/tree/main/charts/kyverno/charts/crds/templates
Thanks!
=> feat: Update Kyverno CRDs to current v1.13.0

cilium.io/ciliumbgppeeringpolicy_v2alpha1.json
This PR updates the CiliumBGPPeeringPolicy `v2alpha1` CRD schema according to: https://github.com/cilium/cilium/blob/5d3bf04c7e2a198e60558224c0c9ab3a747efd03/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumbgppeeringpolicies.yaml
=> feat: update CiliumBGPPeeringPolicy v2alpha1 CRD schema according

logging.openshift.io/clusterlogforwarder_v1.json
Hi,
i tried to use spec.pipelines[0].filterRefs on clusterlogforwarder.logging.openshift.io for an openshift-cluster (4.15) with Openshift logging operator 5.9-stable 
kubeconform complained…
in the cluster the CRD is ready for filters and filterRefs
this is a openAPI-description converted to json-schema from said cluster.
let me know, if there is something i could provide further…
=> add clusterlogforwarder.logging.openshift.io operator version 5.9

resources.teleport.dev/teleportaccesslist_v1.json, resources.teleport.dev/teleportgithubconnector_v3.json, resources.teleport.dev/teleportloginrule_v1.json, resources.teleport.dev/teleportoidcconnector_v3.json, resources.teleport.dev/teleportoktaimportrule_v1.json, resources.teleport.dev/teleportopenssheiceserverv2_v1.json, resources.teleport.dev/teleportopensshserverv2_v1.json, resources.teleport.dev/teleportprovisiontoken_v2.json, resources.teleport.dev/teleportrole_v5.json, resources.teleport.dev/teleportrole_v6.json, resources.teleport.dev/teleportrolev6_v1.json, resources.teleport.dev/teleportrolev7_v1.json, resources.teleport.dev/teleportsamlconnector_v2.json, resources.teleport.dev/teleportuser_v2.json
Generated from [v17.0.1](https://github.com/gravitational/teleport/tree/v17.0.1/integrations/operator/config/crd/bases):
```bash
cd resources.teleport.dev
TELEPORT_VERSION=17.0.1
OPENAPI2JSONSCHEMA=https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
curl -s -L https://github.com/gravitational/teleport/archive/refs/tags/v$TELEPORT_VERSION.tar.gz | tar xvz
python3 <(curl "$OPENAPI2JSONSCHEMA") "teleport-$TELEPORT_VERSION"/integrations/operator/config/crd/bases/*.yaml
rm -rf "teleport-$TELEPORT_VERSION"
```
=> fix: update Teleport CRDs

opentelemetry.io/instrumentation_v1alpha1.json, opentelemetry.io/opampbridge_v1alpha1.json, opentelemetry.io/opentelemetrycollector_v1alpha1.json, opentelemetry.io/opentelemetrycollector_v1beta1.json
These CRDs were generated using 
```
dependencies:
- name: opentelemetry-operator
repository: https://open-telemetry.github.io/opentelemetry-helm-charts
version: 0.74.3
```
deployed on a local kubernetes environment (Docker desktop), exported with `crd-extractor.sh` and tested locally with an object kind: OpenTelemetryCollector v1beta1 and instrumentation. I did not validate the other version/object kind
opentelemetrycollector_v1beta1
```
#valid collector
kubeconform -summary  -schema-location ~/.datree/crdSchemas/opentelemetrycollector_v1beta1.json -strict  /tmp/eventhub/otel-eventhub/charts/open/templates/collector.yaml
Summary: 1 resource found in 1 file - Valid: 1, Invalid: 0, Errors: 0, Skipped: 0
#removing a needed field
kubeconform -summary  -schema-location …
```
=> Update opentelemetry.io schemas to the latest chart 0.74.3

dynamodb.services.k8s.aws/backup_v1alpha1.json, dynamodb.services.k8s.aws/globaltable_v1alpha1.json, dynamodb.services.k8s.aws/table_v1alpha1.json, services.k8s.aws/adoptedresource_v1alpha1.json, services.k8s.aws/fieldexport_v1alpha1.json
```sh
git clone https://github.com/aws-controllers-k8s/dynamodb-controller --depth 1 --branch v1.2.15 && \
kubectl kustomize dynamodb-controller/config/crd/ > crd.yaml && \
python3 /dev/stdin crd.yaml | \
rm -rf dynamodb-controller
```
=> update AWS DynamoDB CRDs

Utilities/crd-extractor.sh
I may have missed it earlier, but I was curious why my outputs didn’t display the nice grouping of CRDs. After some digging, I found [issue #147](https://github.com/datreeio/CRDs-catalog/issues/147#issuecomment-1502885415), which clarified that my Mac was running Bash version 3.x. Once I upgraded to Bash 4+ using Homebrew, everything worked as expected.
To help others avoid this issue, I added a check to ensure compatibility. If you’re facing a similar problem, upgrading Bash to version 4+ should resolve it!
` brew install bash`
And added this to my `~/.zshrc`
```
BASH=$1
if [ -z $BASH ]; then
BASH=/opt/homebrew/bin/bash
fi
```
=> fix(utilities): Check if the bash version is 4+

opentelemetry.io/opentelemetrycollector_v1alpha1.json, opentelemetry.io/opentelemetrycollector_v1beta1.json
Removes `managementState` as a required field in the OpentelemetryCollector CRDs since it has a default value in the CRD.
Fixes #430
=> fix: remove opentelemetry managementState required field

ceph.rook.io/cephblockpool_v1.json, ceph.rook.io/cephblockpoolradosnamespace_v1.json, ceph.rook.io/cephcluster_v1.json, ceph.rook.io/cephcosidriver_v1.json, ceph.rook.io/cephfilesystem_v1.json, ceph.rook.io/cephfilesystemmirror_v1.json, ceph.rook.io/cephnfs_v1.json, ceph.rook.io/cephobjectstore_v1.json, ceph.rook.io/cephobjectstoreuser_v1.json, ceph.rook.io/cephobjectzone_v1.json, ceph.rook.io/cephrbdmirror_v1.json, objectbucket.io/objectbucket_v1alpha1.json, objectbucket.io/objectbucketclaim_v1alpha1.json
Follow https://github.com/datreeio/CRDs-catalog/pull/436
```
git clone https://github.com/rook/rook.git --depth 1 --branch v1.16.0 && \
make crds -C rook && \
echo '{"Values": {"crds": {"enabled": true}}}' | gomplate -c .=stdin:///in.json -f rook/deploy/charts/rook-ceph/templates/resources.yaml > crd.yaml && \
rm -rf rook
```
note:
- final crds are not stored in the repositories. …
=> Update rook.io CRD

infrastructure.cluster.x-k8s.io/ocicluster_v1beta1.json, infrastructure.cluster.x-k8s.io/ocicluster_v1beta2.json, infrastructure.cluster.x-k8s.io/ociclusteridentity_v1beta1.json, infrastructure.cluster.x-k8s.io/ociclusteridentity_v1beta2.json, infrastructure.cluster.x-k8s.io/ociclustertemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/ociclustertemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimachine_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimachine_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimachinepool_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimachinepool_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimachinepoolmachine_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimachinepoolmachine_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimachinetemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimachinetemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedcluster_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedcluster_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedclustertemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedclustertemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedcontrolplane_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedcontrolplane_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedcontrolplanetemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedcontrolplanetemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedmachinepool_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedmachinepool_v1beta2.json, infrastructure.cluster.x-k8s.io/ocimanagedmachinepooltemplate_v1beta1.json, infrastructure.cluster.x-k8s.io/ocimanagedmachinepooltemplate_v1beta2.json, infrastructure.cluster.x-k8s.io/ocivirtualmachinepool_v1beta1.json, infrastructure.cluster.x-k8s.io/ocivirtualmachinepool_v1beta2.json
CRD location: https://github.com/oracle/cluster-api-provider-oci/tree/main/config/crd
```
git clone https://github.com/oracle/cluster-api-provider-oci.git --depth 1 --branch main && \
kubectl kustomize cluster-api-provider-oci/config/crd/ > crd.yaml && \
rm -rf cluster-api-provider-oci
```
=> Add cluster api OCI CRD

postgresql.cnpg.io/backup_v1.json, postgresql.cnpg.io/cluster_v1.json, postgresql.cnpg.io/database_v1.json, postgresql.cnpg.io/pooler_v1.json, postgresql.cnpg.io/publication_v1.json, postgresql.cnpg.io/subscription_v1.json
Source of CRDs: https://github.com/cloudnative-pg/charts
```
vgrdkv@ubuntu:/Users/vgrdkv/Downloads/tmp$ helm upgrade --install cnpg   --namespace cnpg-system   --create-namespace   cnpg/cloudnative-pg
Release "cnpg" does not exist. Installing it now.
NAME: cnpg
LAST DEPLOYED: Wed Dec 25 11:51:01 2024
NAMESPACE: cnpg-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CloudNativePG operator should be installed in namespace "cnpg-system".
You can now create a PostgreSQL cluster with 3 nodes as follows:
cat <<EOF | kubectl apply -f -
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
name: cluster-example
spec:
instances: 3
storage:
size: 1Gi
EOF
kubectl get -A cluster
vgrdkv@ubuntu:/Users/vgrdkv/Downloads/tmp$ ./
crd-extractor.sh  get_helm.sh …
```
=> Update postgresql.cnpg.io CRDs

Utilities/crd-extractor.sh
* Fetch CRDs in parallel
* Avoid use of associative array
* Handle space in file path
=> Improve crd-extractor script

policy.sigstore.dev/clusterimagepolicy_v1alpha1.json, policy.sigstore.dev/clusterimagepolicy_v1beta1.json, policy.sigstore.dev/trustroot_v1alpha1.json
[Cosign](https://github.com/sigstore/cosign) signed images can be validated by a [policy-controller](https://github.com/sigstore/policy-controller/)  using CRDs.
CRDs extracted using:
```bash
kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/sigstore/policy-controller/refs/heads/main/config/300-clusterimagepolicy.yaml
kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/sigstore/policy-controller/refs/heads/main/config/300-trustroot.yaml
```
Their docs can be found [here](https://docs.sigstore.dev/policy-controller/overview/).
=> feat: Add cosign policy controller CRDs

fluxcd.controlplane.io/fluxinstance_v1.json, fluxcd.controlplane.io/fluxreport_v1.json, fluxcd.controlplane.io/resourceset_v1.json, fluxcd.controlplane.io/resourcesetinputprovider_v1.json
[Flux](https://github.com/fluxcd/flux2) can be managed by a [flux-operator](https://github.com/controlplaneio-fluxcd/flux-operator) using CRDs.
CRDs extracted using:
```
kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/controlplaneio-fluxcd/flux-operator/refs/heads/main/config/crd/bases/fluxcd.controlplane.io_fluxinstances.yaml
kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/controlplaneio-fluxcd/flux-operator/refs/heads/main/config/crd/bases/fluxcd.controlplane.io_fluxreports.yaml
kubeconform/scripts/openapi2jsonschema.py https://raw.githubusercontent.com/controlplaneio-fluxcd/flux-operator/refs/heads/main/config/crd/bases/fluxcd.controlplane.io_resourcesetinputproviders.yaml
kubeconform/scripts/openapi2jsonschema.py …
```
=> feat: Add flux operator CRDs

source.toolkit.fluxcd.io/gitrepository_v1.json
We started experimenting with `github` as a provider for our source git repository and our CI pipelines started to fail. It looks like the `github` provider is not included in the CRD but it is a valid option now: https://fluxcd.io/flux/components/source/gitrepositories/#provider
You can also see it in their own CRD: https://github.com/fluxcd/source-controller/blob/main/config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml#L106-L114
=> Update gitrepository_v1.json with github provider support

awspca.cert-manager.io/awspcaclusterissuer_v1beta1.json, awspca.cert-manager.io/awspcaissuer_v1beta1.json
This adds the crds from here https://github.com/cert-manager/aws-privateca-issuer/tree/main/charts/aws-pca-issuer/crds
=> feat(cert-manager): add aws acm private ca issuer crds for cert manager

Utilities/auto-update-index.py, Utilities/convert.py, index.yaml
@eyarz I have tried to make an auto-updater script.
I also have also reworked the structure of the index file a bit:
- The collection is still grouped by organisation (e.g. `aadpodidentity.k8s.io`)
- Within that grouping, I removed `org` and `githubOrg`.
- Within each organisation group, there was another grouping, which I flattened.
- I kept the fields `apiVersion`, `kind`, `filename`, and `name`. The rest I removed.
- I don't think I need the `name`, but I thought maybe you needed it? It corresponds to the key of the grouping that I flattened.
In general, the reason for removing the data I removed above is:
- I could not deduct the missing data from the files.
- I failed to see the value of the data – but perhaps you have a need for this?
- I kind of doubt it since the `index.yaml` was …
=> Auto update index yaml

README.md, Utilities/crd-extractor.sh, Utilities/openapi2jsonschema.py
Changes:
- Use -euo pipefail
- Use mktemp to create a standard tmp dir.
- Clean up using trap.
- Use downloaded/committed openapi2jsonschema.py script (instead of downloading from  github/yannh/kubeconform)
- Wait for background jobs to end.
=> Rework crd extractor a bit

Utilities/crd-extractor.sh
When running the crd-extractor.sh for the first time I saw the following error.
```
❯ ./Utilities/crd-extractor.sh
the python3 module 'yaml' is required, and is not installed on your machine.
./Utilities/crd-extractor.sh: line 34: read: `Do you wish to install this program? (y/n) ': not a valid identifier
```
It seems the prompt must immediately follow the `read -p` parameter.
---
Also the kubeconform hint output at the end was missing the group subdirectory from the schema-location template.
=> Crd extractor fixes

sparkoperator.k8s.io/scheduledsparkapplication_v1beta2.json, sparkoperator.k8s.io/sparkapplication_v1beta2.json
generated with
```bash
rm -rf $HOME/.datree/crdSchemas && \
kind create cluster && \
kubectl create -f https://raw.githubusercontent.com/kubeflow/spark-operator/refs/heads/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml && \
kubectl create -f https://raw.githubusercontent.com/kubeflow/spark-operator/refs/heads/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml && \
./Utilities/crd-extractor.sh && \
cp -r $HOME/.datree/crdSchemas/sparkoperator.k8s.io . && \
kind delete cluster && \
git commit -am "Updated sparkoperator crds to argocd v2.1.1"
```
=> Update spark operator CRDs

actions.github.com/autoscalinglistener_v1alpha1.json, actions.github.com/autoscalingrunnerset_v1alpha1.json, actions.github.com/ephemeralrunner_v1alpha1.json, actions.github.com/ephemeralrunnerset_v1alpha1.json
Signed-off-by: toyamagu-2021 <toyamagu2021@gmail.com>
* https://github.com/actions/actions-runner-controller/releases/tag/gha-runner-scale-set-0.11.0
```console
$ k create -f ./charts/gha-runner-scale-set-controller/crds
customresourcedefinition.apiextensions.k8s.io/autoscalinglisteners.actions.github.com created
customresourcedefinition.apiextensions.k8s.io/autoscalingrunnersets.actions.github.com created
customresourcedefinition.apiextensions.k8s.io/ephemeralrunners.actions.github.com created
customresourcedefinition.apiextensions.k8s.io/ephemeralrunnersets.actions.github.com created
$ ./Utilities/crd-extractor.sh
Fetching list of CRDs...
Fetching CRD 1/4...
Fetching CRD 2/4...
Fetching CRD 3/4...
Fetching CRD 4/4...
JSON schema written to …
```
=> update: actions.github.com to v0.11.0

README.md, Utilities/annotate-yaml.py
I have written a small `annotate-yaml.py` script that I use to, well, annotate yaml documents with `yaml-language-server: $schema=<path>` comments. Adding these comments will help the [Red Hat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) plugin with intellisense and validation.
I updated the README to guide users on how to use this.
=> Annotate yaml script

bitnami.com/sealedsecret_v1alpha1.json
Resolves [sealed-secrets issue](https://github.com/bitnami-labs/sealed-secrets/issues/1717#issuecomment-2797096077)
The CRD contained in the datreeio (and generated by the CRD extractor) incorrectly returns errors for freshly generated sealed secrets as of [the latest change](https://github.com/datreeio/CRDs-catalog/commit/9894f231f39dba4f758f210dc700304f224c9828#diff-8b90cb622f1278648884982a78cda40f55df78ac48c9f4f971271635253b788aL68). Bitnami has confirmed that the CRD used by the sealed secrets controller is correct (see initially linked issue), and that the `spec.template.metadata.creationTimestamp` field is expected. I am setting `/properties/spec/properties/template/properties/metadata/additionalProperties` to true to resolve this issue. I have tested this from my branch with a …
=> Update bitnami.com/sealedsecret CRD to Fix Incorrect Errors

.github/workflows/update-index.yaml
Added GitHub workflow that updates `index.yaml` automatically. It runs on PR merge and if there are any changes in `index.yaml` it creates a PR.
I considered doing some **auto-merge** thing of the PR, but opted not to do it. I am not sure about the security implications of such a thing :)
There is a down side to this approach: The auto-generated PR is oblivious of other PRs. That means:
- If an update-index PR is merged and there are other open CRDs PRs, then these will become outdated:
- If a subsequent CRDs PR is merged "directly", then its subsequent update-index job will result in a PR (with potential conflict) on `index.yaml`
- **Suggestion:** The open PRs need to be rebased on top of `main`. I believe this can be a one-click action in the GH PR UI.
- If multiple CRDs PRs are merged …
=> GH Workflow: Add job to update index.yaml.

karpenter.k8s.aws/ec2nodeclass_v1.json
Karpenter v1.4 introduces SSM parameter resolution for the AMI selector field. 
CRD: https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml#L79-L143 
Documentation: https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms
Change log:  https://github.com/aws/karpenter-provider-aws/releases/tag/v1.4.0 
`add support for custom ssm parameters in amiSelectorTerms (https://github.com/aws/karpenter-provider-aws/pull/7341) https://github.com/aws/karpenter-provider-aws/pull/7341 ([Wesley Yep](https://github.com/aws/karpenter-provider-aws/commit/c41509eaac02b3b1e394cb20fac4eb8879e399f0))`
Following the instructions in https://github.com/datreeio/CRDs-catalog?tab=readme-ov-file#usage, after running `./crd-extractor.sh` …
=> AWS Karpenter CRD add SSMparameter resolution capability to amiSelectorTerms in Ec2NodeClass

monitoring.googleapis.com/clusternodemonitoring_v1.json, monitoring.googleapis.com/clusterpodmonitoring_v1.json, monitoring.googleapis.com/clusterpodmonitoring_v1alpha1.json, monitoring.googleapis.com/clusterrules_v1.json, monitoring.googleapis.com/clusterrules_v1alpha1.json, monitoring.googleapis.com/globalrules_v1.json, monitoring.googleapis.com/globalrules_v1alpha1.json, monitoring.googleapis.com/operatorconfig_v1.json, monitoring.googleapis.com/operatorconfig_v1alpha1.json, monitoring.googleapis.com/podmonitoring_v1.json, monitoring.googleapis.com/podmonitoring_v1alpha1.json, monitoring.googleapis.com/rules_v1.json, monitoring.googleapis.com/rules_v1alpha1.json
We use Google Managed Prometheus and a variety of these within our Clusters to monitor pods. 
This was generated using the CRD Extractor on a fresh GKE cluster running kubernetes `v1.31.7`
- [*] I have used the [CRD Extractor](https://github.com/datreeio/CRDs-catalog?tab=readme-ov-file#crd-extractor) tool to generate these CRDs
=> feat: added monitoring.googleapis.com schema using CRD Extractor from a fresh GKE cluster

Utilities/annotate-yaml.py
- Handling of files that includes '---' in strings that are not document separators.
- Better handling of files not having the apiVersion and kind properties present.
=> Minor bugfixes in annotate-yaml.py:

cloud.google.com/computeclass_v1.json
I didn't have the correct bash available where I was working, so I ran `FILENAME_FORMAT="{fullgroup}_{kind}_{version}" ./Utilities/openapi2jsonschema.py` manually after kubectl pulling down the file, hopefully that's ok?  (I know kubeconform consumes the ouput)
=> Add cloud.google.com's ComputeClass CRD

logging.banzaicloud.io/clusterflow_v1alpha1.json, logging.banzaicloud.io/clusterflow_v1beta1.json, logging.banzaicloud.io/clusteroutput_v1alpha1.json, logging.banzaicloud.io/clusteroutput_v1beta1.json, logging.banzaicloud.io/flow_v1alpha1.json, logging.banzaicloud.io/flow_v1beta1.json, logging.banzaicloud.io/fluentbitagent_v1beta1.json, logging.banzaicloud.io/fluentdconfig_v1beta1.json, logging.banzaicloud.io/logging_v1beta1.json, logging.banzaicloud.io/nodeagent_v1beta1.json, logging.banzaicloud.io/output_v1alpha1.json, logging.banzaicloud.io/output_v1beta1.json, logging.banzaicloud.io/syslogngclusteroutput_v1beta1.json, logging.banzaicloud.io/syslogngconfig_v1beta1.json, logging.banzaicloud.io/syslogngoutput_v1beta1.json
Pulled from https://github.com/kube-logging/logging-operator/tree/5.3.0/charts/logging-operator/crds and converted with openapi2jsonschema.py.
=> Update logging.banzaicloud.io CRDs to v5.3.0

Utilities/crd-extractor.sh
Allow specifying a custom output directory for generated CRD schemas by setting the OUTPUT_DIR environment variable. This enables users to generate schemas in their current directory or any specified location instead of the default ~/.datree/crdSchemas.
Also updated the success message to show the actual output directory used and adjusted the example commands to use the correct path.
=> feat: add OUTPUT_DIR environment variable support to crd-extractor.sh

azure.upbound.io/providerconfig_v1beta1.json
Not exactly the CRD Extractor. I ran the following for only extracting the providerconfig - taken from the CRD Extractor script:
```shell
export FILENAME_FORMAT="{fullgroup}_{kind}_{version}"
SCHEMAS_DIR=$(pwd)
python3 ./Utilities/openapi2jsonschema.py https://raw.githubusercontent.com/crossplane-contrib/provider-upjet-azure/refs/heads/main/package/crds/azure.upbound.io_providerconfigs.yaml
for schema in "$SCHEMAS_DIR"/*.json; do             
crdFileName=$(basename "$schema")
crdGroup=$(echo "$crdFileName" | cut -d"_" -f1)
outName=$(echo "$crdFileName" | cut -d"_" -f2-)
mkdir -p "$crdGroup"
mv "$schema" "./$crdGroup/$outName"
done
```
=> add crossplane azure providerconfig.

cert-manager.k8s.cloudflare.com/originissuer_v1.json
Since the last update (v0.8.0), there are new changes in the CRDs, specially in the tokenRef section.
Generated using the documented script in the original PR for this CRD: 
```
python3 /dev/stdin $(
curl -s https://api.github.com/repos/cloudflare/origin-ca-issuer/git/trees/v0.8.0\?recursive\=1 | \
jq -r '.tree[] | select(.path | startswith("deploy/crds/")) | "https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/v0.12.1/" + .path' | \
tr '\n' ' '
) | \
xargs -I {} sh -c 'mkdir -p $(dirname $(echo {} | sed "s|__|/|")) && mv {} $(echo {} | sed "s|__|/|")'
```
=> Update Cloudflare Origin CA Issuer CRDs (v0.12.1)

restate.dev/restatecluster_v1.json, restate.dev/restatedeployment_v1beta1.json
This pull request introduces a new JSON schema definition for the `RestateDeployment` Custom Resource Definition (CRD) in the `restate.dev` API group. The schema provides a structured way to validate and document the configuration for Restate deployments on Kubernetes, specifying required fields and detailed options for deployment, registration, and pod management.
Key additions in the new schema:
**RestateDeployment CRD schema definition:**
* Adds a JSON schema (`restate.dev/restatedeployment_v1beta1.json`) for validating `RestateDeployment` resources, including required fields like `apiVersion`, `kind`, `metadata`, and `spec`.
* Defines the `spec` structure, supporting configuration for pod replicas, revision history, pod template, label selectors, and Restate-specific registration …
=> Add json schema for restate operator cdrs
